project_id = "iwmrtxdzlkasuzutxvhh"

[functions.send-whatsapp]
verify_jwt = false

[functions.notify-store-order]
verify_jwt = false

[functions.whatsapp-evolution]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.nfce-proxy]
verify_jwt = false

[functions.nfce-webhook]
verify_jwt = false

[functions.extract-menu]
verify_jwt = false

[functions.extract-optionals]
verify_jwt = false
