import { lazy } from 'react';

export const Index = lazy(() => import('@/pages/Index'));
export const Products = lazy(() => import('@/pages/Products'));
export const ProductEdit = lazy(() => import('@/pages/ProductEdit'));
export const CadastrosConfiguracoes = lazy(() => import('@/pages/CadastrosConfiguracoes'));
export const Orders = lazy(() => import('@/pages/Orders'));
export const Settings = lazy(() => import('@/pages/Settings'));
export const Menu = lazy(() => import('@/pages/Menu'));
export const NoCompany = lazy(() => import('@/pages/NoCompany'));
export const NotFound = lazy(() => import('@/pages/NotFound'));
export const PDVPage = lazy(() => import('@/pages/PDV'));
export const PaymentMethods = lazy(() => import('@/pages/PaymentMethods'));
export const CashRegisters = lazy(() => import('@/pages/CashRegisters'));
export const TablesConfig = lazy(() => import('@/pages/TablesConfig'));
export const Waiter = lazy(() => import('@/pages/Waiter'));
export const WaitersConfig = lazy(() => import('@/pages/WaitersConfig'));
export const POS = lazy(() => import('@/pages/POS'));
export const SalesReport = lazy(() => import('@/pages/SalesReport'));
export const CashReport = lazy(() => import('@/pages/CashReport'));
export const TefReport = lazy(() => import('@/pages/TefReport'));
export const TefAdm = lazy(() => import('@/pages/TefAdm'));
export const WhatsAppSettings = lazy(() => import('@/pages/WhatsAppSettings'));
export const Changelog = lazy(() => import('@/pages/Changelog'));
export const Fiscal = lazy(() => import('@/pages/Fiscal'));
export const NFCeMonitor = lazy(() => import('@/pages/NFCeMonitor'));
export const EspelhoFiscal = lazy(() => import('@/pages/fiscal/EspelhoFiscal'));
export const Suggestions = lazy(() => import('@/pages/Suggestions'));
export const MenuImport = lazy(() => import('@/pages/MenuImport'));
export const OptionalGroups = lazy(() => import('@/pages/OptionalGroups'));
export const Categories = lazy(() => import('@/pages/Categories'));
export const Subcategories = lazy(() => import('@/pages/Subcategories'));
export const Combos = lazy(() => import('@/pages/Combos'));
export const ComboEdit = lazy(() => import('@/pages/ComboEdit'));
export const CustomerReport = lazy(() => import('@/pages/CustomerReport'));
export const ABCReport = lazy(() => import('@/pages/ABCReport'));
export const SalesCampaigns = lazy(() => import('@/pages/SalesCampaigns'));
export const Customers = lazy(() => import('@/pages/Customers'));
export const Suppliers = lazy(() => import('@/pages/Suppliers'));
export const PDVV2 = lazy(() => import('@/pages/PDVV2'));
export const PDVV2ComandasHistorico = lazy(() => import('@/pages/PDVV2ComandasHistorico'));
export const CouponsPage = lazy(() => import('@/pages/Coupons'));
export const MesaQR = lazy(() => import('@/pages/MesaQR'));
export const FrenteCaixa = lazy(() => import('@/pages/FrenteCaixa'));
export const FrenteCaixaLista = lazy(() => import('@/pages/FrenteCaixaLista'));
export const FrenteCaixaConfiguracoes = lazy(() => import('@/pages/FrenteCaixaConfiguracoes'));
export const Receitas = lazy(() => import('@/pages/financeiro/Receitas'));
export const Despesas = lazy(() => import('@/pages/financeiro/Despesas'));
export const FluxoCaixa = lazy(() => import('@/pages/financeiro/FluxoCaixa'));
export const Inadimplencia = lazy(() => import('@/pages/financeiro/Inadimplencia'));
const financePlaceholder = (name: keyof typeof import('@/pages/financeiro/FinancePlaceholderPages')) =>
  lazy(() =>
    import('@/pages/financeiro/FinancePlaceholderPages').then((m) => ({ default: m[name] })),
  );

export const ReceitasRelatorios = financePlaceholder('ReceitasRelatorios');
export const DespesasRelatorios = financePlaceholder('DespesasRelatorios');
export const ReceitasConfiguracoes = financePlaceholder('ReceitasConfiguracoes');
export const DespesasConfiguracoes = financePlaceholder('DespesasConfiguracoes');
export const PlanosDeContas = financePlaceholder('PlanosDeContas');
export const CentrosDeCustos = financePlaceholder('CentrosDeCustos');
export const EstoqueRelatorio = lazy(() => import('@/pages/EstoqueRelatorio'));
export const InventarioContagem = lazy(() => import('@/pages/InventarioContagem'));
export const InventarioLivro = lazy(() => import('@/pages/InventarioLivro'));
export const InventarioCMV = lazy(() => import('@/pages/InventarioCMV'));
export const InventarioKardex = lazy(() => import('@/pages/InventarioKardex'));
export const RelatoriosHub = lazy(() => import('@/pages/RelatoriosHub'));
export const DfeManifestacao = lazy(() => import('@/pages/compras/DfeManifestacao'));
export const PurchaseImportXml = lazy(() => import('@/pages/compras/PurchaseImportXml'));
export const PurchaseInvoices = lazy(() => import('@/pages/compras/PurchaseInvoices'));
export const Compras = lazy(() => import('@/pages/compras/Compras'));
export const ComprasRelatorios = lazy(() => import('@/pages/compras/ComprasRelatorios'));
export const ComprasConfiguracoes = lazy(() => import('@/pages/compras/ComprasConfiguracoes'));
export const NovaCompra = lazy(() => import('@/pages/compras/NovaCompra'));
export const NFeList = lazy(() => import('@/pages/nfe/NFeList'));
export const NFeEmissaoAvulsa = lazy(() => import('@/pages/nfe/NFeEmissaoAvulsa'));
export const AdminDashboard = lazy(() => import('@/pages/admin/AdminDashboard'));
export const IntegrationsPage = lazy(() => import('@/pages/admin/IntegrationsPage'));
export const CompanyModulesPage = lazy(() => import('@/pages/admin/CompanyModulesPage'));
export const SuggestionsAdmin = lazy(() => import('@/pages/admin/SuggestionsAdmin'));
export const ResellersPage = lazy(() => import('@/pages/admin/ResellersPage'));
export const AdminSettings = lazy(() => import('@/pages/admin/AdminSettings'));
export const CampaignSettings = lazy(() => import('@/pages/admin/CampaignSettings'));
export const MediaKitAdmin = lazy(() => import('@/pages/admin/MediaKitAdmin'));
export const ResellerMediaKit = lazy(() => import('@/pages/reseller/ResellerMediaKit'));
export const ResellerHome = lazy(() => import('@/pages/reseller/ResellerHome'));
export const ResellerLojas = lazy(() => import('@/pages/reseller/ResellerLojas'));
export const ResellerConfiguracoes = lazy(() => import('@/pages/reseller/ResellerConfiguracoes'));
