/**
 * Versão atual do Comanda Tech.
 * Incremente a cada release e adicione entrada em RELEASES (mais recente no topo).
 *
 * SemVer:
 *  - MAJOR: mudanças grandes / quebras
 *  - MINOR: nova feature
 *  - PATCH: correção de bug
 */
export const VERSION = "1.39.0-beta";
export const RELEASE_DATE = "2026-06-26"; // YYYY-MM-DD (America/Sao_Paulo)
export const CODENAME = "Frente de Caixa: importar mesa/comanda do PDV V2";

export interface Release {
  version: string;
  date: string; // YYYY-MM-DD
  codename?: string;
  changes: string[];
}

export const RELEASES: Release[] = [
  {
    version: "1.39.0-beta",
    date: "2026-06-26",
    codename: "Frente de Caixa: importar mesa/comanda do PDV V2",
    changes: [
      "Frente de Caixa › Importar mesa: agora lista também as mesas/comandas abertas direto no PDV V2 (tabela tabs), e não apenas as mesas abertas via QR Code público (origin='mesa_qr'). Resolve o caso em que a mesa estava aberta no PDV V2 e não aparecia para importar.",
      "Cada item da lista mostra 'Mesa N' (quando há mesa física vinculada) ou 'Comanda N', com o total somado dos itens ainda não pagos da comanda.",
      "Ao finalizar a venda no Frente de Caixa com uma mesa importada do PDV V2: a comanda é fechada (status='closed') e a mesa física é liberada (status='available') — mesmo comportamento do botão 'Fechar comanda' do PDV V2.",
      "Botão 'Importar mesa' agora também aparece para lojas com o módulo Mesas (PDV V2) ativo, não só para quem tem Cardápio Mesa QR.",
      "Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento, impressão, PDV V2 (venda), Pedido Express ou cobrança — apenas no diálogo de importação do FC e no fechamento pós-venda quando a fonte é uma comanda.",
    ],
  },
  {
    version: "1.38.5-beta",
    date: "2026-06-26",
    codename: "Impressão: rollback para v8.39 (estável em produção)",
    changes: [
      "auto_printer.py revertido para v8.39 — versão estável e validada em vários clientes em produção. v8.40/v8.41/v8.42/v8.43 (tentativas de correção para Windows 11 com Python 3.12) foram descartadas.",
      "Lojas que estavam estáveis na v8.39 não precisam baixar nada novo — continuam exatamente como estavam.",
      "Cozinha da Ruiva e demais máquinas com Windows 11 quebrado: baixar o auto_printer.py v8.39 em Configurações → Impressão e substituir em C:\\ComandaTech.",
    ],
  },
  {
    version: "1.38.4-beta",
    date: "2026-06-26",
    codename: "Impressão: hotfix v8.43 (TextOut volta a funcionar)",
    changes: [
      "auto_printer.py v8.43: corrige regressão da v8.42 que parava a impressão automática no Windows — o método hDC.TextOutW não existe no PyCDC do pywin32 e gerava AttributeError silencioso a cada cupom.",
      "Trocadas todas as chamadas hDC.TextOutW(...) por hDC.TextOut(...). No Python 3 todas as strings já são Unicode, então o TextOut do pywin32 chama internamente a variante Unicode do GDI — junto com o 'charset': 1 das fontes (mantido), os acentos continuam saindo corretos.",
      "Nenhuma mudança em layout, fontes, margens, TEF, PinPad, NFC-e, PDV V2, Pedido Express, Frente de Caixa ou cobrança. Basta baixar o auto_printer.py v8.43 em Configurações → Impressão e reiniciar o iniciar_impressao.cmd.",
    ],
  },
  {
    version: "1.38.3-beta",
    date: "2026-06-26",
    codename: "Impressão: acentos voltam a sair corretos (Unicode no GDI)",
    changes: [
      "auto_printer.py v8.42: corrige cupons com acentos saindo como 'Cafª', 'Sandu\u00d8che', 'Opt\u0131es', 'AM\u207fNDOAS' em máquinas com Python 3.12 + pywin32 novo (caso da Cozinha da Ruiva).",
      "Todas as chamadas hDC.TextOut(...) foram trocadas por hDC.TextOutW(...) (variante Unicode explícita do GDI) e todas as fontes do recibo (Courier New normal, regular, bold-big, obs, descrição e grupo) ganharam 'charset': 1 (DEFAULT_CHARSET).",
      "Resultado: o cupom sai exatamente como na v8.39 — mesmo layout, mesma fonte, mesmas margens, mesmos negritos — só com os acentos certos novamente.",
      "Nenhuma mudança em layout, espaçamento, fontes, tamanhos, observações invertidas ou bordas; nenhuma alteração em TEF, PinPad, NFC-e, PDV V2, Pedido Express, Frente de Caixa ou cobrança.",
    ],
  },
  {
    version: "1.38.2-beta",
    date: "2026-06-25",
    codename: "Impressão Windows 11: correção DLL pywin32",
    changes: [
      "Pacote de impressão local atualizado para corrigir o erro 'DLL load failed while importing win32print' no Windows 11: o instalador agora remove pywin32 antigo, limpa cache e reinstala pywin32 sem cache.",
      "Novo verificador verificar_pywin32.py valida requests, win32print, win32ui, win32gui e carrega automaticamente a pasta pywin32_system32 no caminho de DLLs do processo.",
      "Inicializador de impressão v1.3 executa o verificador antes de iniciar e dispara o instalador v1.3 automaticamente se detectar dependência quebrada.",
      "auto_printer.py atualizado para v8.41 com preparação runtime das DLLs do pywin32 antes de imprimir, evitando loop de falha na fila por importação parcial do pywin32.",
    ],
  },
  {
    version: "1.38.1-beta",
    date: "2026-06-25",
    codename: "Impressão Windows 11: instalador alternativo CMD",
    changes: [
      "Pacote de impressão local atualizado para Windows 11: novos arquivos instalar_impressao.cmd e iniciar_impressao.cmd para máquinas que não reconhecem .bat ao dar duplo clique.",
      "Instalador de impressão agora exibe versão v1.2, entra automaticamente na pasta correta e localiza o pywin32_postinstall pelo caminho real do Python detectado.",
      "Inicializador de impressão agora exibe versão v1.2 e tenta auto-reparar dependências (requests/pywin32) antes de iniciar o auto_printer.py.",
      "auto_printer.py atualizado para v8.40, documentando o uso preferencial dos arquivos .cmd no Windows 11 problemático.",
    ],
  },
  {
    version: "1.38.0-beta",
    date: "2026-06-25",
    codename: "Cancelar NFC-e + venda: estorno TEF automático e badges no relatório",
    changes: [
      "Cancelar NFC-e na Lista do PDV: se o pagamento foi via TEF (PinPad), o estorno é disparado automaticamente após o cancelamento na SEFAZ.",
      "Após cancelar a NFC-e, o sistema pergunta: 'Cancelar venda também (reverte caixa e estoque)' ou 'Manter como pré-venda'.",
      "Novo item no menu de ações: 'Cancelar pré-venda', disponível quando a venda não tem NFC-e válida — também estorna TEF e exige motivo (mínimo 20 caracteres).",
      "Relatório de Vendas: 4 badges distintos — NFC-e (verde), NFC-e cancelada (âmbar), Pré-venda (azul) e Cancelada (vermelho).",
      "Vendas canceladas saem dos totais de 'Total de Vendas' e 'Total Faturado', mas continuam visíveis na quebra fiscal e na listagem.",
    ],
  },
  {
    version: "1.37.0-beta",
    date: "2026-06-25",
    codename: "Frente de Caixa: menu de ações por venda (estilo GWeb)",
    changes: [
      "Lista do PDV: cada venda agora tem um menu de ações (três pontinhos) com Marcar, Emitir NFC-e, Consultar status, Copiar chave de acesso, Visualizar DANFCE, Visualizar XML, Salvar documento e Cancelar NFC-e.",
      "Checkbox de marcação por linha (preparado para futuras ações em massa).",
      "Cancelamento de NFC-e com diálogo dedicado pedindo justificativa de no mínimo 15 caracteres.",
      "Visualizar XML abre o arquivo em nova aba; Salvar documento baixa o XML autorizado.",
      "Consultar status sincroniza o registro com a SEFAZ via nfce-proxy.",
      "Nenhuma alteração em nfce-proxy, runTefPayment, pinpadService, tef-webservice, TEF v1.0/v1.1/v1.2-beta, Multi-Pagamento v1.6/v1.7, PDV V2 ou Pedido Express.",
    ],
  },
  {
    version: "1.36.0-beta",
    date: "2026-06-25",
    codename: "Frente de Caixa: seletor TEF (Crédito/Débito/Parcelado)",
    changes: [
      "Checkout do Frente de Caixa: linha de pagamento TEF agora mostra um seletor de modalidade (Crédito à vista / Débito / Parcelado) assim que recebe valor > 0 — antes toda venda TEF era enviada fixa como 'Crédito à vista', sem perguntar.",
      "Quando 'Parcelado' é escolhido, aparece campo numérico de parcelas (2 a 18, default 2). A modalidade e o número de parcelas são repassados ao runTefPayment via tef_options.",
      "Estado por linha: cada linha TEF (caso haja mais de uma) tem sua própria modalidade/parcelas, idêntico ao PDV V2.",
      "Nenhuma alteração em runTefPayment, pinpadService, tef-webservice, TEF v1.0/v1.1/v1.2-beta, PDV V2, Pedido Express, Cobrança, Multi-Pagamento ou NFC-e — apenas UI do FrenteCaixaCheckoutDialog.",
    ],
  },
  {
    version: "1.32.4-beta",
    date: "2026-06-22",
    codename: "Checkout FC: Enter não pula Cliente",
    changes: [
      "Checkout da Frente de Caixa: corrigido Enter no campo de pagamento para avançar para Cliente sem disparar o atalho global que pulava direto para Informações adicionais.",
    ],
  },
  {
    version: "1.32.3-beta",
    date: "2026-06-22",
    codename: "Checkout FC: Enter avança com tolerância de centavos",
    changes: [
      "Checkout FC: Enter agora considera tolerância de centavos ao validar se o valor pago já cobre o total, evitando falha por arredondamento decimal.",
    ],
  },
  {
    version: "1.32.2-beta",
    date: "2026-06-22",
    codename: "Checkout FC: Enter avança quando valor já preenchido",
    changes: [
      "Checkout FC etapa 1: Enter com campo vazio preenche o valor restante; Enter novamente (ou com valor já lançado e nada mais a alocar) avança para a etapa Cliente.",
    ],
  },
  {
    version: "1.32.1-beta",
    date: "2026-06-22",
    codename: "Checkout FC: Enter só preenche + etapas anteriores ficam visíveis",
    changes: [
      "Checkout da Frente de Caixa: ao pressionar uma letra (A/B/C…) e Enter no campo de pagamento, agora o valor restante é apenas preenchido — o wizard NÃO avança mais automaticamente para a etapa Cliente. Para avançar use o botão 'Próximo' ou Ctrl+2.",
      "Etapas anteriores do checkout permanecem visíveis acima da etapa atual (estilo Gweb): ao avançar para Cliente, o resumo dos pagamentos fica fixo logo abaixo do passo 1; ao avançar para Observações, o cliente selecionado também fica visível.",
    ],
  },
  {
    version: "1.32.0-beta",
    date: "2026-06-22",
    codename: "Lista do Frente de Caixa em cards (estilo Gweb)",
    changes: [
      "Lista do PDV (Frente de Caixa › Lista) reformulada para o layout em cards do Gweb: avatar do cliente, linha de metadados (Número / Série / Emissão / Total + forma de pagamento entre parênteses) e linha de badges abaixo.",
      "Novo badge de TIPO de documento: laranja 'PV' para pré-venda e amarelo 'NFC-e' para venda fiscal — antes o tipo ficava implícito no badge de status fiscal.",
      "Novo badge verde 'Pré-venda concluída' nas vendas sem NFC-e (espelha o Gweb).",
      "Status fiscal agora aparece como badge sólido colorido: verde 'Autorizado o uso da NF-e' / vermelho 'Pendente de emissão do documento fiscal' / âmbar pendente / cinza cancelada / vermelho destrutivo rejeitada.",
      "Numeração sequencial humana por loja: nova coluna pv_numero em pdv_sales preenchida automaticamente por trigger (contador por company_id). Cada nova venda do PDV recebe número 1, 2, 3… independente do número da NFC-e. Vendas antigas seguem mostrando o id curto (#ABC123) como fallback.",
      "Ações inline (Ver detalhes, Emitir NFC-e retroativo, Reimprimir DANFE) preservadas — nenhuma mudança em TEF, PinPad, NFC-e, Multi-Pagamento, impressão ou checkout.",
    ],
  },
  {
    version: "1.31.3-beta",
    date: "2026-06-22",
    codename: "Relatório de Vendas: tipo NFC-e × Pré-venda",
    changes: [
      "Relatório de Vendas agora identifica cada venda como 'NFC-e' (operador escolheu emitir nota) ou 'Pré-venda' (sem NFC-e). A classificação usa o fiscal_mode gravado em pdv_sales.",
      "Novo bloco de resumo: contagem e faturamento separados para 'Vendas com NFC-e' e 'Pré-vendas (sem NFC-e)'.",
      "Nova coluna 'Tipo' na lista 'Vendas no Período' com badge colorido (verde = NFC-e, âmbar = Pré-venda) ao lado da Origem.",
      "Pedidos do cardápio entregues herdam o fiscal_mode da pdv_sale vinculada; pedidos sem pdv_sale são tratados como pré-venda.",
      "Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento, impressão, PDV V2, Pedido Express, Frente de Caixa (venda) ou cobrança — apenas leitura no relatório.",
    ],
  },
  {
    version: "1.31.2-beta",
    date: "2026-06-22",
    codename: "Frente de Caixa: remoção do menu Receitas (placeholder)",
    changes: [
      "Removido o item 'Recebimento' do rail lateral do Frente de Caixa e a rota /frente-caixa/recebimento — a tela era um placeholder inspirado no Gweb antigo, prometia 'Receitas' mas só listava vendas já finalizadas (e duplicava PV + NFC-e da mesma venda).",
      "Os dados úteis dessa tela já estão disponíveis no Relatório de Fechamento de Caixa (totais por forma de pagamento) e no Relatório de Vendas — nada se perde.",
      "Quando o módulo de Contas a Receber for implementado, criaremos uma tela 'Receitas' de verdade (parcelas, vencimentos, baixas, juros/multa).",
      "Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento, impressão, PDV V2, Pedido Express, Frente de Caixa (venda) ou cobrança.",
    ],
  },
  {
    version: "1.31.1-beta",
    date: "2026-06-22",
    codename: "Frente de Caixa: pós-venda NFC-e com status na tela",
    changes: [
      "Frente de Caixa: ao clicar 'Salvar NFC-e', o checkout fecha e abre um overlay 'Emitindo NFC-e…' enquanto aguarda a SEFAZ — antes a tela ficava em branco e o operador não sabia se a nota tinha saído.",
      "Logo depois abre o mesmo diálogo pós-venda do PDV V2: faz polling SEFAZ até autorizar/rejeitar, exibe nº da NFC-e e oferece 'Imprimir DANFE'. Em rejeição, tenta reenviar 1x automaticamente.",
      "Respeita a configuração 'Imprimir cupom ao finalizar' (auto_print_on_finish) do PDV/Frente de Caixa: quando ligada, o DANFE imprime sozinho e a janela fecha em 3s; quando desligada, o operador escolhe imprimir e fecha em 10s.",
      "TEF segue inalterado: vendas com cartão/PIX via maquininha continuam emitindo NFC-e automaticamente no fluxo TEF próprio (v1.0/v1.1/v1.2-beta).",
      "Nenhuma mudança em PDV V2, Pedido Express, Cobrança, OrderCardChargeDialog, Multi-Pagamento (v1.6/v1.7) nem nos payloads enviados ao nfce-proxy.",
    ],
  },
  {
    version: "1.31.0-beta",
    date: "2026-06-22",
    codename: "Frente de Caixa: abertura de caixa + fechamento por módulo",
    changes: [
      "Frente de Caixa: o banner 'Nenhum caixa aberto' agora tem um botão 'Abrir Caixa' inline — o operador da loja só-Mercado abre o caixa sem precisar ir em Financeiro → Caixa.",
      "Modelo confirmado: um caixa por loja. Quando a loja tem PDV + Mercado, o mesmo caixa é compartilhado (já garantido pelo índice cash_registers_one_open_per_company); abrir pelo PDV libera o Frente de Caixa e vice-versa.",
      "Vendas do Frente de Caixa agora são marcadas com source_module='mercado' em pdv_sales; vendas do PDV V2, Pedido Express e Cobrança continuam como 'pdv' (default).",
      "Relatório de fechamento de caixa ganhou seção 'Totais por módulo' (PDV / Comandas × Mercado / Frente de Caixa) — aparece apenas quando há vendas dos dois módulos no mesmo caixa.",
      "Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento, impressão, PDV V2, Pedido Express ou cobrança.",
    ],
  },
  {
    version: "1.30.0-beta",
    date: "2026-06-22",
    codename: "Nova Compra manual (estilo GWeb)",
    changes: [
      "Nova tela /compras/nova: cadastro manual de nota de compra alinhado 1:1 ao GWeb, com 5 seções (Cabeçalho, Fornecedor, Produtos, Pagamentos, Transporte) e rodapé fixo Voltar / Salvar e concluir / Salvar.",
      "Cabeçalho: Número, Modelo (default 55), Série, Chave de acesso (44 dígitos, opcional), Emissão (data+hora), Entrada (data+hora) e Natureza da operação com badge 'Entrada'.",
      "Fornecedor: combobox com busca por nome ou CNPJ na lista de fornecedores ativos. Quando nenhum é encontrado, atalho direto pra /fornecedores.",
      "Produtos: bloqueado até o fornecedor ser informado. Após: linhas editáveis com combobox de produto, quantidade, valor unitário e total por linha (verde) + total geral no cabeçalho da seção.",
      "Pagamentos: aparece apenas quando o total dos produtos > 0. Linhas com forma de pagamento (da lista cadastrada) + valor. Botão 'Adicionar pagamento' já sugere o valor restante. Aviso visual se a soma não bater (amarelo) ou se bater (verde).",
      "Transporte: select com 6 tipos de frete (Sem Transporte default, emitente, destinatário, terceiros, próprios).",
      "'Salvar e concluir' grava a nota (status='lancada', origem='manual') e dispara apply_stock_movement (entrada) pra cada item com produto vinculado — mesmo mecanismo do Importar XML.",
      "'Salvar' grava como rascunho (status='rascunho') sem mexer em estoque, permitindo retomar depois.",
      "Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento, impressão, PDV V2, Pedido Express, Frente de Caixa ou cobrança — apenas nova tela de entrada de compras.",
    ],
  },
  {
    version: "1.29.0-beta",
    date: "2026-06-22",
    codename: "Hub Compras estilo GWeb (Fase 2)",
    changes: [
      "Hub /compras alinhado 1:1 ao GWeb: removidos subtítulo e barra de paginação do topo; paginação agora aparece só no rodapé (estilo GWeb).",
      "Sidebar direita ganhou 'Relatórios' em Acesso (placeholder 'em breve') e bloco 'Configurações' separado (placeholder 'em breve'). Item 'Compras' renomeado para 'Lista' (mesma rota).",
      "Empty state redesenhado: mascote + texto 'Não há nada a exibir por aqui…' + botão 'Nova compra' que leva direto pra tela de cadastro manual.",
      "Novo FAB '+' laranja flutuante no canto inferior direito da tela /compras com tooltip 'Cadastrar nota de compra' (atalho pra /compras/nova).",
      "Rotas /compras/relatorios e /compras/configuracoes registradas, protegidas pelo FrenteCaixaGuard, exibindo placeholder até a Fase 2B/2C entrar.",
      "Tela /compras/nova (cadastro manual de nota de compra estilo GWeb) entra na próxima etapa — esta release entrega apenas os ajustes de UI da lista.",
      "Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento, impressão, PDV V2, Pedido Express, Frente de Caixa ou cobrança — apenas UI do hub /compras.",
    ],
  },
  {
    version: "1.28.0-beta",
    date: "2026-06-22",
    codename: "Movimentações + Hub Compras (estilo GWeb)",
    changes: [
      "Novo menu lateral 'Movimentações' agrupando Pedidos, Comandas, PDV, Frente de Caixa e Compras — alinhado ao padrão do GWeb. Os itens continuam exatamente onde estavam, só ficaram reunidos num único bloco.",
      "Novo hub /compras (lojas com Mercado ativo): tela única estilo GWeb com sidebar de Acesso (Compras / Manifestação eletrônica) e Ações (Importar XML / XML do mês). A coluna principal lista as NF-e de entrada com busca, ordenação e paginação.",
      "Botão 'XML do mês' nas Compras: baixa em .zip todos os XMLs das NF-e de entrada importadas no mês escolhido (reaproveita o diálogo do Frente de Caixa, agora com fonte 'NFC-e' ou 'NF-e de Entrada').",
      "Grupo 'Compras' antigo (com 3 sub-itens) foi removido do menu — virou um único atalho 'Compras' dentro de Movimentações que abre o novo hub. Rotas antigas (/compras/manifestacao, /compras/importar-xml, /compras/entradas) continuam funcionando.",
      "Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento, impressão, PDV V2, Pedido Express ou cobrança — fluxos de venda intocados.",
    ],
  },
  {
    version: "1.27.0-beta",
    date: "2026-06-21",
    codename: "Compras: Manifestação Eletrônica DF-e + NF-e de Entrada",
    changes: [
      "Novo menu 'Compras' (visível em lojas com módulo Mercado ativo) com três itens: Manifestação Eletrônica, NF-e de Entrada e Importar XML.",
      "Manifestação Eletrônica (/compras/manifestacao): lista todas as NF-e recebidas contra o CNPJ da loja (DF-e) com filtros (status, busca por chave/emitente/CNPJ), badges de status (Pendente/Ciência/Confirmada/Desconhecida/Não realizada/Entrada/Cancelada), menu de ações por documento (Ciência, Confirmação, Desconhecimento, Não realizada, Download XML, Importar pro estoque, Copiar chave, Ignorar) e FAB 'Sincronizar SEFAZ' que dispara um loop até esgotar a fila da FiscalFlow.",
      "Importar XML (/compras/importar-xml): wizard que aceita XML já manifestado (a partir do DF-e) ou upload manual do computador, faz parse 100% no navegador (DOMParser), exibe cabeçalho do fornecedor + grid de itens. Para cada item, permite mapear a um produto existente (por GTIN/descrição) ou criar produto novo (preenche nome, GTIN, NCM, CFOP, unidade e custo do XML automaticamente).",
      "Ao confirmar entrada: cria fornecedor (se novo, vincula por CNPJ), grava purchase_invoices + purchase_invoice_items e dispara apply_stock_movement para cada item mapeado (tipo 'entrada', referência ao purchase_invoice). XML é arquivado no bucket privado 'dfe-xmls'.",
      "NF-e de Entrada (/compras/entradas): histórico de notas lançadas com fornecedor, número, série, valor e data.",
      "Integrações ganhou novo campo 'ID da Empresa na Fiscal Flow' (companies.fiscalflow_empresa_id) ao lado do token. Necessário para usar a Manifestação. Token FiscalFlow é reaproveitado.",
      "Novo edge function 'dfe-fiscalflow-proxy' (ações: sync, mirror, manifestar, download_xml) — token nunca é exposto ao navegador. Multi-tenancy validado por user_belongs_to_company em todas as chamadas.",
      "Tabelas novas (RLS por company_id): dfe_documentos, dfe_eventos, purchase_invoices, purchase_invoice_items. Bucket privado dfe-xmls.",
      "Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento, impressão, PDV V2, Pedido Express, Frente de Caixa, Garçom ou cobrança — fluxos de venda intocados.",
    ],
  },
  {
    version: "1.26.0-beta",
    date: "2026-06-21",
    codename: "Cadastro de produtos por tipo (Cardápio / Mercado / Ambos)",
    changes: [
      "Novo campo 'Tipo do produto' no cadastro: Cardápio (pratos/lanches), Mercado (conveniência) ou Ambos. Para lojas existentes, todos os produtos foram migrados automaticamente baseando-se na visibilidade atual — zero impacto.",
      "Categoria agora é OPCIONAL para itens de tipo Mercado — se não escolher, cai em 'Geral' automaticamente. Pratos do Cardápio seguem com categoria obrigatória.",
      "Botão 'Novo Produto' (em lojas com Mercado ativo) abre um seletor: Cardápio / Mercado / Ambos. Cada tipo abre o formulário com defaults apropriados (estoque pré-ativado no Mercado, etc).",
      "Botão inline '+ Criar nova categoria' direto no formulário de produto — sem precisar sair da tela.",
      "Bloco 'Dados Fiscais' (NCM, CFOP, CEST, origem, regra tributária) agora é recolhível, abrindo só quando precisar editar. Continua disponível para Cardápio e Mercado — qualquer item pode emitir NFC-e.",
      "As 3 toggles antigas (Cardápio digital / PDV / Garçom) viraram 'Visibilidade avançada', recolhida por padrão. A visibilidade é derivada automaticamente do tipo escolhido.",
      "Lista de produtos: novos chips de filtro Todos / Cardápio / Mercado / Ambos, e cada produto recebe um badge colorido indicando o tipo.",
      "Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento, impressão, PDV V2, Pedido Express ou cobrança.",
    ],
  },
  {
    version: "1.25.0-beta",
    date: "2026-06-21",
    codename: "Perfil Só-Mercado + Hub de Relatórios",
    changes: [
      "Novo hub de Relatórios (cards em /relatorios) acessível pelo menu 'Relatórios' do Frente de Caixa — escolha visual entre Vendas, Caixa, Clientes, Curva ABC, TEF (oculto se PinPad não configurado) e Estoque (oculto se Mercado desativado).",
      "Hub adapta a sidebar automaticamente: lojas com PDV V2 veem a sidebar do PDV V2; demais usam a sidebar padrão.",
      "Novo item 'Relatório de Estoque' no submenu Relatórios das sidebars (AppSidebar e PDV V2), exibido apenas quando o módulo Mercado está ativo.",
      "Novo módulo 'Cardápio Digital / Pedidos' no painel do Super Admin — ATIVO por padrão em todas as lojas existentes (zero impacto). Desativar apenas em lojas que serão SÓ Mercado.",
      "Perfil 'Só Mercado' (Mercado ativo + Cardápio desativado): a home cai direto na Frente de Caixa e a sidebar fica enxuta, escondendo Pedidos, Cardápio, Mesas, Garçom, Cupons, Combos, Adicionais, Subcategorias, WhatsApp Ordering e Importar Cardápio.",
      "Carrinho 🛒 (F8) agora aparece também no AppLayout para lojas híbridas (Mercado + Cardápio) que não usam PDV V2 — antes só funcionava dentro do PDV V2.",
      "Rotas /frente-caixa/* e /estoque agora são protegidas: redirecionam para a home se a loja não tem o módulo Mercado ativo.",
      "Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento, impressão, Pedido Express, PDV V2 ou cobrança.",
    ],
  },
  {
    version: "1.24.0-beta",
    date: "2026-06-21",
    codename: "Atalho rápido para Frente de Caixa (FAB + F8)",
    changes: [
      "Novo botão flutuante de carrinho 🛒 no canto inferior direito para lojas com módulo Mercado ativo — abre a Frente de Caixa em uma aba dedicada com um clique.",
      "Atalho de teclado global F8 abre a Frente de Caixa de qualquer tela do painel (ignorado quando o foco está em campos de texto).",
      "A aba da Frente de Caixa é nomeada e reaproveitada: apertar F8 várias vezes foca a aba existente em vez de abrir novas. Ideal para operação multi-monitor (gerente em pedidos, operador no caixa).",
      "Escondido automaticamente em telas mobile e em lojas sem o módulo Mercado.",
      "Nenhuma alteração em rotas, sidebar, TEF, PinPad, NFC-e, Multi-Pagamento, PDV V2, Pedido Express ou impressão — é apenas um atalho de UI.",
    ],
  },
  {
    version: "1.23.0-beta",
    date: "2026-06-19",
    codename: "Cadastros > Combos (Beta — piloto Rei do Açaí)",
    changes: [
      "Corrigido no cardápio público: adicionais pagos escolhidos dentro do fluxo de combo agora são somados ao valor do combo no carrinho, subtotal, total do pedido e envio do pedido.",
      "Nova aba 'Cadastros > Combos' (irmã de Categorias, Produtos e Adicionais) para montar combos a partir de produtos existentes — cada combo tem foto, nome, código, GTIN, preço fixo, categorias do cardápio e visibilidade independente em PDV, Cardápio e Garçom.",
      "Editor com 3 abas: Geral (dados básicos e foto), Itens (busca por nome/código + quantidade) e Fiscal (NCM/CFOP/CEST/regra tributária, usados só no modo 'kit comercial').",
      "Modo fiscal padrão: 'Kit explodido' — na NFC-e cada item componente sai como uma linha fiscal própria com a tributação do produto original (regra correta para combos com itens de tributação diferente, ex.: açaí + bebida). Preço do combo é rateado proporcionalmente entre os itens.",
      "Aviso suave quando os itens têm regras tributárias diferentes (não bloqueia).",
      "Rollout isolado: novo módulo 'Combos (Beta)' no painel do Super Admin. Liberado manualmente apenas para a loja Rei do Açaí no piloto. Nas demais lojas, nada muda.",
      "Nenhuma alteração em TEF, PinPad, NFC-e (somente leitura de combos quando o módulo estiver ativo), Multi-Pagamento, impressão, PDV V2, Pedido Express, Frente de Caixa ou cobrança.",
    ],
  },
  {
    version: "1.22.10-beta",
    date: "2026-06-15",
    codename: "Menu lateral: operação e fiscal reorganizados",
    changes: [
      "Corrigido o menu lateral real usado pelas telas do PDV: 'Frente de Caixa' agora aparece no Menu Principal quando o módulo Mercado está ativo, junto de PDV, Pedidos e Comandas.",
      "Fiscal e NFC-e Monitor saíram do Menu Principal e voltaram para um grupo próprio 'Fiscal', evitando misturar operações de caixa com configurações/monitor fiscal.",
      "Ajuste apenas de navegação/visibilidade de menu. Nenhuma alteração em TEF, PinPad, NFC-e, Frente de Caixa, emissão fiscal, impressão ou cobrança.",
    ],
  },
  {
    version: "1.22.9-beta",
    date: "2026-06-15",
    codename: "Comandas: sync realtime do garçom/QR no caixa",
    changes: [
      "Corrigido: quando o garçom (app mobile) ou o cliente (Cardápio Mesa QR) adicionava um item na comanda, o PDV V2 do operador de caixa não atualizava sozinho — era preciso apertar 'Atualizar' manualmente.",
      "Agora a lista de itens da comanda (`tab_items`) também é escutada em tempo real, com um pequeno atraso de 1,5s para evitar o bug antigo de o item próprio 'piscar' ao ser adicionado pelo próprio caixa.",
      "Vale para todas as lojas com módulo de Garçom e/ou Cardápio Mesa QR ativos. Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento, impressão ou cobrança.",
    ],
  },
  {
    version: "1.22.8-beta",
    date: "2026-06-15",
    codename: "Histórico de comandas + auditoria de cancelamento",
    changes: [
      "Nova página 'Histórico de Comandas' no PDV V2 (logo abaixo de Pedidos), com filtro de data e busca, para acessar comandas finalizadas mesmo após o fechamento do caixa. Permite reimprimir venda, comprovante TEF, reimprimir/cancelar NFC-e — sem permitir cancelar a venda (regra: só dentro do caixa atual).",
      "Cancelamento de venda no diálogo 'Comandas Finalizadas' agora exige motivo (mínimo 20 caracteres) e registra automaticamente quem cancelou, data/hora e se houve estorno TEF na nova tabela `pdv_sale_cancellations`.",
      "Cards de vendas canceladas (no PDV e no Histórico) passam a exibir Motivo / Por / Em e, quando aplicável, a marca 'TEF estornado'.",
      "Nenhuma mudança em TEF, PinPad, NFC-e ou no fluxo de cobrança; o histórico é somente leitura para caixas já fechados.",
    ],
  },
  {
    version: "1.22.7-beta",
    date: "2026-06-15",
    codename: "Relatório TEF consolida PDV V2",
    changes: [
      "Corrigido o Relatório TEF PinPad para consolidar também vendas finalizadas direto no PDV V2, além dos pedidos da tabela de pedidos.",
      "No dia 14/06, transações TEF gravadas apenas na venda PDV agora aparecem no relatório junto das transações vinculadas a pedidos, sem depender da origem da cobrança.",
      "Ajuste restrito ao relatório: não altera TEF, PinPad, NFC-e, cobrança ou estorno; maquininha móvel não é classificada como TEF.",
    ],
  },
  {
    version: "1.22.6-beta",
    date: "2026-06-15",
    codename: "Fechamento consolida todo pagamento",
    changes: [
      "Corrigida a base do fechamento de caixa para consolidar todo pagamento finalizado/cobrado no período do caixa, independentemente da origem: balcão, Pedido Express, online/cardápio, retirada, delivery ou mesa.",
      "Pedidos cobrados que não tenham `pdv_sale` vinculada também entram no relatório de fechamento pela forma de pagamento registrada, evitando vendas legítimas ficarem fora da conciliação.",
      "Ajuste feito no carregador central do fechamento, sem alterar TEF, PinPad, NFC-e ou o fluxo de cobrança.",
    ],
  },
  {
    version: "1.22.5-beta",
    date: "2026-06-15",
    codename: "Fechamento espelha movimento de caixa",
    changes: [
      "Corrigido o fechamento/relatório de caixa para usar o movimento físico completo: abertura + vendas em dinheiro + suprimentos - sangrias.",
      "A tela, o valor gravado no fechamento, a diferença e a impressão detalhada agora usam a mesma conta, evitando divergência entre Relatório de Caixa e Movimento de Caixa.",
    ],
  },
  {
    version: "1.22.4-beta",
    date: "2026-06-15",
    codename: "Caixa: dinheiro esperado corrigido",
    changes: [
      "Corrigido o Relatório de Caixa/fechamento para calcular o esperado em Dinheiro pelas vendas em dinheiro reais, incluindo pedidos em dinheiro entregues que apareceram no filtro mas ainda não tinham lançamento PDV vinculado.",
      "A abertura do caixa permanece separada do total de vendas em dinheiro, evitando misturar saldo inicial com recebimentos do dia.",
    ],
  },
  {
    version: "1.22.3-beta",
    date: "2026-06-15",
    codename: "Printer V2: grupos liberados na origem",
    changes: [
      "Corrigido o ponto que ainda deixava Margen e demais lojas V2 imprimirem adicionais como lista plana: cardápio público e Pedido Express agora enviam os grupos estruturados para o layout V2/V3, não apenas para a I9.",
      "Com isso, pizzas com 2+ grupos passam a sair com o rótulo do grupo (■ sublinhado) e os itens abaixo; pedidos com 1 grupo seguem mostrando só os itens com '+'.",
      "Não altera TEF, PinPad, NFC-e, Multi-Pagamento, cobranças ou layouts V1. O auto_printer.py v8.39 preserva o rótulo do grupo mesmo quando há só 1 grupo real.",
    ],
  },
  {
    version: "1.22.2-beta",
    date: "2026-06-15",
    codename: "Printer V2 liberado para lojas V2",
    changes: [
      "auto_printer.py v8.38: os ajustes v8.32–v8.37 foram liberados para todas as lojas com Layout V2 ativo em Configurações, incluindo Margen.",
      "Inclui rótulo de grupo com ■ sublinhado, endereço invertido, adicionais com '+', 'Pronto até' no recibo V2 e modo compacto/economia de papel no GDI.",
      "Lojas em V1 ou V3 continuam intactas. TEF, PinPad, NFC-e, Multi-Pagamento e cobranças não foram alterados.",
    ],
  },
  {
    version: "1.22.1-beta",
    date: "2026-06-14",
    codename: "Cupom secreto: validação no checkout corrigida",
    changes: [
      "Cupons marcados como SECRETO (ex.: BRASIL15) agora funcionam normalmente quando o cliente cola o código no carrinho — antes a validação só olhava os cupons públicos visíveis no banner e devolvia 'Cupom inválido ou expirado'.",
      "Agora, ao aplicar um código manualmente, o cardápio consulta o banco direto pelo código informado (respeitando empresa, ativo, validade e limite de uso).",
    ],
  },
  {
    version: "1.22.0-beta",
    date: "2026-06-14",
    codename: "Fechamento de caixa: multi-pagamento separado por forma",
    changes: [
      "Vendas pagas com várias formas (multi-pagamento) agora aparecem no relatório/impressão de fechamento de caixa divididas por forma — cada forma com o valor exato cobrado, em vez de tudo somado na forma de maior valor.",
      "Nova tabela `pdv_sale_payments` registra o split de cada venda multi-pagamento (PDV V2, Pedido Express e Cobrar Comanda/Mesa).",
      "Nenhuma alteração em TEF, PinPad, NFC-e ou no fluxo de cobrança em si — apenas a forma como o relatório de fechamento exibe.",
    ],
  },
  {
    version: "1.21.18-beta",
    date: "2026-06-14",
    codename: "Printer: borda direita segura no V2 compacto",
    changes: [
      "auto_printer.py v8.37: corrigido o cálculo dos retângulos desenhados via GDI no V2 compacto da Lancheria da i9. A borda direita do cabeçalho e blocos pretos agora é limitada à área imprimível, evitando corte na lateral direita.",
      "Mudança isolada ao V2 compacto da Lancheria da i9; sem alteração em TEF, PinPad, NFC-e, Multi-Pagamento, cobranças ou demais lojas.",
    ],
  },
  {
    version: "1.21.17-beta",
    date: "2026-06-14",
    codename: "Comanda: rodapé curto em todos os caminhos",
    changes: [
      "Corrigido o ponto real que ainda imprimia '--- FIM DO PEDIDO ---' na comanda de produção: o rodapé agora sai como '--- FIM ---' também no layout V2, no texto fallback e no layout V3.",
      "Sem alteração em TEF, PinPad, NFC-e, Multi-Pagamento, cobranças ou regras de pedido.",
    ],
  },
  {
    version: "1.21.16-beta",
    date: "2026-06-14",
    codename: "Comanda V2: rodapé encurtado para caber em 1 linha",
    changes: [
      "Comanda de produção V2: '--- FIM DO PEDIDO ---' era largo demais e quebrava em 2 linhas na bobina 80mm com a fonte bold. Encurtado para '--- FIM ---', que cabe folgado em 1 linha — economia adicional de papel.",
      "Sem impacto em V1, V3, recibo do cliente, TEF, PinPad, NFC-e ou Multi-Pagamento. Não precisa reinstalar o auto_printer.py.",
    ],
  },
  {
    version: "1.21.15-beta",
    date: "2026-06-14",
    codename: "Comanda V2: '--- FIM DO PEDIDO ---' em 1 linha",
    changes: [
      "Comanda de produção V2: o rodapé '--- FIM DO PEDIDO ---' estava ocupando 2 linhas visuais (uma para o tracejado de borda e outra para o texto). Removi a borda tracejada — os próprios traços do texto já servem de separador — e o rodapé agora ocupa apenas 1 linha, economizando mais alguns milímetros de papel por pedido.",
      "Nenhuma alteração em V1, V3, recibo do cliente, TEF, PinPad, NFC-e ou Multi-Pagamento. Não precisa reinstalar o auto_printer.py.",
    ],
  },
  {
    version: "1.21.14-beta",
    date: "2026-06-14",
    codename: "Impressão compacta real no instalador v8.36",
    changes: [
      "Corrigido o ponto real da economia de papel na Lancheria da i9: o instalador v8.35 estava recebendo HTML compacto, mas a impressão automática via GDI convertia o HTML em texto e ainda mantinha linhas vazias artificiais entre quase todos os blocos.",
      "O auto_printer.py agora sai como v8.36 e, somente no layout V2 da Lancheria da i9, remove essas linhas vazias extras antes de enviar para a impressora, mantendo o mesmo tamanho de fonte e o mesmo conteúdo do pedido.",
      "Também reduzi o padding interno da caixa do cabeçalho no caminho GDI compacto, sem alterar TEF, PinPad, NFC-e, Multi-Pagamento, nfce-proxy, frente de caixa ou cobranças.",
    ],
  },
  {
    version: "1.21.13-beta",
    date: "2026-06-14",
    codename: "Recibo V2 modo compacto (economia de papel — piloto I9)",
    changes: [
      "Recibo V2 e comanda de produção V2 ganharam um 'modo compacto' que reduz o consumo de bobina SEM alterar o tamanho da fonte. Estimativa: 18% a 22% menos papel por pedido.",
      "O que mudou: linhas mais próximas umas das outras (line-height menor), margens em cima/embaixo de cada item reduzidas, caixinha preta de observação mais enxuta, cabeçalho e rodapé com menos espaço.",
      "O que NÃO mudou: tamanho da fonte (continua igual), linha tracejada separando os itens (mantida), 5 linhas em branco no fim do recibo para anotação manual (mantidas).",
      "Rollout ISOLADO à Lancheria da i9 (piloto) — demais lojas com layout V2 continuam imprimindo no formato atual até validação. Lojas V1 e V3 não foram tocadas.",
      "Nenhuma alteração em TEF v1.0/v1.1/v1.2-beta, PinPad, NFC-e, Multi-Pagamento v1.6/v1.7, nfce-proxy, Frente de Caixa, OrderCardChargeDialog ou runMultiPayment.",
    ],
  },
  {
    version: "1.21.12-beta",
    date: "2026-06-14",
    codename: "Pronto até liberado para todas as lojas com layout V2",
    changes: [
      "O campo 'Pronto até' (previsão de quando o pedido fica pronto) agora aparece no recibo e na comanda de produção de TODAS as lojas com layout V2 marcado em Configurações — antes era exclusivo da Lancheria da i9.",
      "Cálculo automático: horário de criação + (máximo do 'Prazo estimado de entrega' − 10 min). Cada loja configura o prazo em Configurações → WhatsApp. Fallback de 30 min se não configurado.",
      "Lojas com layout V1 continuam sem o campo. V3 continua com 'Pronto até' apenas na I9 (layout exclusivo).",
    ],
  },
  {
    version: "1.21.11-beta",
    date: "2026-06-14",
    codename: "Recibo V2: melhorias liberadas para todas as lojas com layout V2",
    changes: [
      "As melhorias de impressão antes restritas à Lancheria da i9 foram liberadas para TODAS as lojas com layout V2 marcado em Configurações.",
      "Passa a valer em qualquer loja V2: rótulo do grupo de adicionais com ■ sublinhado, endereço de entrega em bloco invertido, valor dos adicionais no recibo (ex.: '+ LEITE CONDENSADO  R$ 3,00') e observação do item em invertido.",
      "Aplicado nas 3 origens de recibo V2: PDV V2 / Pedido Express (pdvV2Print.ts), comanda de produção V2 (printProductionTicket.ts) e reimpressão após edição (OrderEditDialog).",
      "Lojas com layout V1 ou V3 continuam intactas. Para enxergar as melhorias, baixe o auto_printer.py v8.34 na máquina da loja.",
    ],
  },
  {
    version: "1.21.10-beta",
    date: "2026-06-14",
    codename: "Recibo V2 (I9): valor dos adicionais aparece no recibo",
    changes: [
      "Recibo V2 da Lancheria da i9: adicionais com valor agora mostram o preço no recibo (ex.: '+ LEITE CONDENSADO  R$ 3,00'). Antes o valor só aparecia na comanda de produção — no recibo o '+ R$' era removido.",
      "Aplicado nas 3 origens de recibo V2: pedidos do cardápio online (auto_printer.py), PDV V2 / Pedido Express (pdvV2Print.ts) e reimpressão após edição (OrderEditDialog).",
      "Isolado por company_id da Lancheria da i9 — demais lojas continuam idênticas. Não muda comanda V2, V1, V3, TEF, PinPad, NFC-e ou Multi-Pagamento.",
      "NÃO precisa reinstalar o auto_printer.py — a formatação é só de texto dentro dos marcadores [ADD] já existentes (versão do script continua v8.32).",
    ],
  },
  {
    version: "1.21.9-beta",
    date: "2026-06-14",
    codename: "auto_printer: rótulo de grupo + endereço invertido (I9)",
    changes: [
      "Comanda de produção V2 e recibo V2 (Lancheria da i9): o rótulo do grupo de adicionais agora aparece prefixado com ■, sublinhado e com capitalização original (ex.: ■ Adicionais:) em vez de CAPS sem destaque. Itens dos grupos continuam em CAPS com '+ ITEM'.",
      "Quando o produto tem apenas 1 grupo de adicionais, o rótulo é omitido — imprime só '+ ITEM' direto, evitando ruído visual.",
      "Endereço de entrega passou a sair em bloco invertido (fundo preto / texto branco), igual ao nome do cliente — fica imediatamente abaixo do nome no recibo e no cabeçalho da comanda.",
      "Tudo isolado por company_id da Lancheria da i9 — demais lojas que rodam o auto_printer.py continuam idênticas. V1, V3, TEF, PinPad, NFC-e, Multi-Pagamento e nfce-proxy não foram tocados.",
      "Requer atualização do auto_printer.py na máquina da i9 (Configurações → Impressora → baixar/reinstalar). Versão do script: v8.32.",
    ],
  },
  {
    version: "1.21.8-beta",
    date: "2026-06-13",
    codename: "auto_printer: '+' nos adicionais (I9)",
    changes: [
      "auto_printer.py (Lancheria da i9): o prefixo dos adicionais na comanda de produção e no recibo (V1/V2 e Pedido Express) mudou de '>> ' para '+ ' — visual mais clean e semântico de 'acrescentado'.",
      "Isolado por company_id no próprio script: outras lojas que rodam o auto_printer.py continuam imprimindo '>> ' como antes — zero regressão.",
      "Requer atualização do auto_printer.py na máquina da i9 (Configurações → Impressora → baixar/reinstalar). Versão do script: v8.31.",
      "Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento, recibo V3 ou demais lojas.",
    ],
  },
  {
    version: "1.21.7-beta",
    date: "2026-06-13",
    codename: "auto_printer: 'Pronto até' Pedido Express (I9)",
    changes: [
      "auto_printer.py (Lancheria i9): recibos gerados localmente pelo script (Pedido Express e demais layouts V1/V2) agora exibem 'Pronto até: HH:MM' no cabeçalho, mesma fórmula da comanda (criação + prazo máximo − 10 min).",
      "Isolado por company_id — outras lojas que rodam o auto_printer.py não sofrem nenhuma alteração no recibo.",
      "Requer atualização do auto_printer.py na máquina da i9 (reinstalar/baixar o script). Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento ou recibo V3.",
    ],
  },
  {
    version: "1.21.6-beta",
    date: "2026-06-13",
    codename: "Recibo V2: 'Pronto até' (I9)",
    changes: [
      "Recibo do pedido V2 (somente Lancheria da i9): 'Pronto até: HH:MM' em destaque logo abaixo do Cliente, mesmo cálculo da comanda (criação + prazo máximo − 10 min).",
      "Nenhuma alteração nas demais lojas, recibo V1/V3, comanda de produção, TEF, PinPad, NFC-e ou Multi-Pagamento.",
    ],
  },
  {
    version: "1.21.5-beta",
    date: "2026-06-13",
    codename: "V2: 'Pronto até' no cabeçalho (I9)",
    changes: [
      "Comanda de produção V2 e recibo V3 (somente Lancheria da i9): removida a linha redundante 'Criado em' (a data/hora já aparece no cabeçalho). Logo abaixo da data/hora agora sai 'Pronto até: HH:MM' em destaque.",
      "Cálculo do 'Pronto até' continua usando o prazo estimado configurado em WhatsApp (máximo − 10 min). Nenhuma alteração para as demais lojas, V1 ou layouts não-V2/V3.",
      "Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento ou nfce-proxy.",
    ],
  },
  {
    version: "1.21.4-beta",
    date: "2026-06-13",
    codename: "V2: grupos de adicionais nomeados (I9)",
    changes: [
      "Comanda de produção V2 (somente Lancheria da i9): os adicionais agora saem agrupados pelo nome do grupo (ex.: 'SABORES:', 'BORDAS:', 'MOLHOS:') em vez de uma lista única misturada. Mesma informação que o OrderCard já mostra na tela.",
      "Fallback preservado: pedidos sem grupos estruturados continuam saindo no formato antigo do V2 (lista plana com '>>'). Nenhuma mudança para as demais lojas.",
      "Nenhuma alteração em V1, V3, recibo do cliente, TEF, PinPad, NFC-e ou Multi-Pagamento.",
    ],
  },
  {
    version: "1.21.3-beta",
    date: "2026-06-13",
    codename: "Impressão: printer.py respeita V2 na I9",
    changes: [
      "Correção operacional (Lancheria da i9): o backend já estava gerando a fila nova em V2, mas o computador da loja ainda podia estar com um printer.py antigo (v5.x) em modo 'piloto i9', que recriava o recibo direto no layout V3.",
      "O printer.py baixável agora sai como v8.30, grava também o layout atual selecionado (V1/V2/V3) e reforça que V3 só é usado quando print_layout='v3' — nunca mais por slug/company_id da I9.",
      "Configurações → Impressora agora mostra o layout ativo e avisa para substituir o printer.py antigo em C:\\ComandaTech quando a loja ainda estiver imprimindo V3 com V2 selecionado.",
      "Nenhuma alteração em TEF, PinPad, NFC-e, Multi-Pagamento, nfce-proxy ou nos desenhos visuais dos layouts V1/V2/V3.",
    ],
  },
  {
    version: "1.21.2-beta",
    date: "2026-06-13",
    codename: "Impressão: seletor V1/V2/V3 volta a funcionar na I9",
    changes: [
      "Correção (Lancheria da i9): o recibo do PDV V2 / Pedido Express / Cobrança ignorava o seletor 'Layout de Impressão' das Configurações e forçava sempre V3 por causa de uma trava antiga por company_id. Agora o seletor V1/V2/V3 volta a funcionar normalmente — escolher V2 imprime V2, escolher V3 imprime V3.",
      "A comanda de produção do PDV V2 (balcão/online) também passou a respeitar o `print_layout` salvo (antes caía sempre em V1 por não repassar o campo). Pedido Express, Menu público e MesaQR já passavam corretamente — sem mudança.",
      "Nenhuma alteração em V1/V2/V3 visualmente: as funções de renderização ficam intactas. A correção é apenas em qual delas é escolhida na hora de imprimir.",
      "NFC-e, TEF v1.0/v1.1/v1.2-beta, PinPad, runMultiPayment, OrderCardChargeDialog e nfce-proxy NÃO foram tocados.",
    ],
  },
  {
    version: "1.21.1-beta",
    date: "2026-06-13",
    codename: "Impressão V3: adicionais agrupados (Lancheria I9)",
    changes: [
      "Impressão V3 (Lancheria da i9): comanda de produção e recibo agora mostram os adicionais SEPARADOS POR GRUPO, com o rótulo do grupo em negrito — igual ao que já aparece no card do pedido. Ex.: 'Sabores da sua Pizza: CAMARÃO R$12,00, FILÉ R$8,00' em uma linha, 'Borda: Chocolate R$10,00' em outra.",
      "Aplicado às 3 origens de pedido: cardápio público (/r/i9), MesaQR e Pedido Express. PDV V2 (import de comanda/mesa) também herda o recibo corrigido automaticamente.",
      "Rollout ISOLADO por company_id — só a Lancheria da i9 recebe o novo formato. Margen Pizzaria, Império do Açaí, Bon Appetit, Rei do Açaí, Scubidão e Vânia Lanches continuam EXATAMENTE iguais até validação manual.",
      "Layouts V1 e V2 não foram alterados. NFC-e, TEF, PinPad, runMultiPayment, OrderCardChargeDialog, nfce-proxy e fluxos homologados não foram tocados.",
    ],
  },
  {
    version: "1.21.0-beta",
    date: "2026-06-12",
    codename: "Frente de Caixa: Pré-venda + NFC-e retroativa (Fases 1+2+3)",
    changes: [
      "Configurações da Frente de Caixa → bloco 'Comportamento' ganhou nova opção 'Ação ao salvar a venda (fiscal)': 'Salvar como pré-venda (sem NFC-e)', 'Salvar e emitir NFC-e' ou 'Perguntar sempre'. Padrão: Perguntar sempre — não altera comportamento das lojas existentes.",
      "Fase 1 — pdv_sales ganhou a coluna fiscal_mode ('fiscal' | 'nao_fiscal', default 'nao_fiscal'). Toda venda da Frente de Caixa agora é classificada explicitamente como pré-venda ou venda fiscal. Histórico permanece intacto (vendas antigas ficam como 'nao_fiscal').",
      "Fase 2 — quando 'Perguntar sempre' está ativo, o checkout exibe dois botões SALVAR: 'Salvar pré-venda' (sem NFC-e) e 'Salvar + NFC-e' (emite automaticamente após cobrança aprovada). Quando o modo padrão é 'fiscal' ou 'nao_fiscal', aparece um único botão correspondente. A NFC-e é enviada com pagamentos_split (compatível com Multi-Pagamento v1.6/v1.7).",
      "Fase 3 — Lista do PDV (Frente de Caixa → Lista) ganhou botão 'Emitir NFC-e' para vendas sem NFC-e autorizada ou rejeitada/inutilizada. Reaproveita pdv_sale_items, monta o payload e dispara o nfce-proxy. Marca a venda como fiscal_mode='fiscal' após envio e dispara a baixa de estoque pendente quando 'Movimentar estoque apenas na emissão fiscal' está ligado.",
      "Pré-venda continua movimentando estoque e caixa normalmente (a menos que 'Movimentar estoque apenas na emissão fiscal' esteja ligado). A NFC-e retroativa cuida da baixa pendente, sem duplicar movimentações (proteção em applyStockMovementOnce).",
      "Mudança ISOLADA à Frente de Caixa (módulo Mercado). PDV V2, Pedido Express, OrderCardChargeDialog, runMultiPayment, runTefPayment, pinpadService, tef-webservice, nfce-proxy, TEF v1.0/v1.1/v1.2-beta, Multi-Pagamento v1.6/v1.7 NÃO foram tocados. Lojas sem o módulo Mercado não enxergam diferença.",
    ],
  },
  {
    version: "1.20.2-beta",
    date: "2026-06-12",
    codename: "Frente de Caixa: Configurações do PDV (Fase A.2 — Comportamento)",
    changes: [
      "Configurações da Frente de Caixa → bloco 'Comportamento' ganhou 2 novos ajustes (Fase A.2): 'Movimentar estoque apenas na emissão fiscal' e 'Ação ao salvar a venda' (Não imprimir / Imprimir automaticamente / Perguntar sempre). Defaults preservam comportamento atual.",
      "Quando 'Movimentar estoque apenas na emissão fiscal' está ligado: a Frente de Caixa NÃO baixa estoque ao registrar a venda — a baixa fica reservada à emissão da NFC-e (próxima fase). Útil para quem só quer movimentar estoque com documento fiscal autorizado.",
      "'Ação ao salvar a venda' substitui o toggle on/off da Fase A por 3 modos: 'off' (padrão, não imprime), 'auto' (dispara impressão automática) e 'ask' (pergunta ao operador via confirm). Lojas que já tinham o toggle on são migradas automaticamente para 'auto'.",
      "Itens FORA da Fase A.2 (Gweb tem, Comanda Tech não suporta hoje): Gerar financeiro, Sugerir vendedor, Usar tabela de preço, Pagamentos digitais na pré-venda, Mesclar pré-vendas — todos dependem de módulos ainda inexistentes (contas a receber, comissão, tabelas de preço, pré-venda).",
      "Mudança ISOLADA: nada de PDV V2, Pedido Express, OrderCardChargeDialog, runMultiPayment, runTefPayment, pinpadService, tef-webservice, nfce-proxy, TEF v1.0/v1.1/v1.2-beta foi tocado.",
    ],
  },
  {
    version: "1.20.1-beta",
    date: "2026-06-12",
    codename: "Frente de Caixa: Configurações do PDV (Fase A.1)",
    changes: [
      "Configurações da Frente de Caixa → bloco 'Controle de caixa' ganhou 2 novos toggles (Fase A.1): 'Bloquear fechamento com venda pendente (itens no carrinho)' e 'Imprimir relatório de fechamento automaticamente'. Ambos com default DESLIGADO — comportamento atual preservado.",
      "Quando 'Bloquear fechamento com venda pendente' está ligado E a loja tem o módulo Mercado ativo: a tela Caixas impede fechar o caixa enquanto houver itens no carrinho da Frente de Caixa (contagem persistida em localStorage 'frenteCaixa.cartPendingCount'). Mostra toast com a quantidade de itens pendentes.",
      "Quando 'Imprimir relatório de fechamento automaticamente' está ligado E a loja tem o módulo Mercado ativo: assim que o caixa é fechado com sucesso na tela Caixas, o Rel. de fechamento (mesmo do rail da Frente de Caixa) é impresso automaticamente — respeitando 'Fechamento de caixa cego' quando ligado.",
      "Mudança ISOLADA: nada de PDV V2, Pedido Express, OrderCardChargeDialog, runMultiPayment, runTefPayment, pinpadService, tef-webservice, nfce-proxy, TEF v1.0/v1.1/v1.2-beta, Multi-Pagamento v1.6/v1.7 foi tocado. Lojas sem módulo Mercado não enxergam diferença na tela Caixas.",
    ],
  },
  {
    version: "1.20.0-beta",
    date: "2026-06-11",
    codename: "Frente de Caixa: Configurações do PDV (Fase A — estilo Gweb)",
    changes: [
      "Configurações da Frente de Caixa ganhou 4 novos blocos espelhando o PDV do Gweb (Fase A). Todos os toggles vivem em `pdv_settings` e são consumidos APENAS pela Frente de Caixa — PDV V2, Pedido Express, Cobrança e TEF continuam intocados.",
      "Bloco 'Controle de caixa': (a) Exigir caixa aberto para vender — quando desligado, suprime o banner 'Nenhum caixa aberto' e libera abrir o checkout sem caixa; (b) Fechamento de caixa cego — esconde 'Valor esperado' e 'Diferença' no Rel. de fechamento; (c) Exigir motivo em sangria/suprimento — torna o campo Motivo obrigatório no diálogo de movimentações de caixa.",
      "Bloco 'Itens de venda': (a) Bloquear venda de item sem preço — impede adicionar produto com preço ≤ 0 ao carrinho; (b) Permitir alterar preço na venda — quando desligado, desabilita o item 'Alterar preço' do menu de contexto e o atalho Home; (c) Confirmar quando a quantidade adicionada for maior que N — pede confirmação ao usar o multiplicador (ex.: 50*7891234567890).",
      "Bloco 'Comportamento': prepara as flags Imprimir cupom automaticamente ao finalizar, Imprimir 2ª via automaticamente, Abrir gaveta no pagamento em dinheiro e Limpar tela após finalizar venda — gravadas em `pdv_settings` para uso pela próxima fase de impressão da Frente de Caixa.",
      "Bloco 'Cupom — extras': Mostrar logo da loja, Mostrar QR Code de avaliação e URL do QR de avaliação — também gravadas, prontas para a impressão dedicada da Frente de Caixa.",
      "Defaults preservam 100% do comportamento atual: nenhuma loja sente diferença até ligar/desligar manualmente os toggles na tela Configurações do PDV.",
      "Itens FORA da Fase A (ficam para fases B/C/D): ordenação/visibilidade de pagamentos, intermediador NFC-e, código de barras de balança, Gerar financeiro, Tabela de preço, Boleto e Crédito Loja.",
    ],
  },
  {
    version: "1.19.0-beta",
    date: "2026-06-11",
    codename: "Frente de Caixa: rail fixo estilo Gweb + Receitas + Rel. fechamento ampliado",
    changes: [
      "Rail lateral direito do Frente de Caixa foi reorganizado para espelhar o PDV do Gweb: agora INICIA SEMPRE ABERTO (preferência persistida em localStorage 'frenteCaixa.menuOpen'), com toggle »/« para recolher manualmente e atalho F10 para alternar.",
      "Conteúdo enxuto e focado APENAS no fluxo de venda do PDV: card 'Acessar' (Lista, Relatórios, Recebimento, ECONF em stand-by), card 'Ações' (Inutilizar numeração, XML do mês, Contingência desativada, Sangria, Suprimento, Rel. de fechamento) e card 'Configurações' (Configurações do PDV).",
      "Itens globais (Pedidos, Clientes, Produtos, Estoque, NFC-e Monitor, Preferências, Formas de pagamento, Impressão, Configurações da NFC-e) foram REMOVIDOS do rail — continuam acessíveis pelo menu principal, sem duplicação.",
      "Nova tela 'Receitas' (rota /frente-caixa/recebimento) — equivalente ao Recebimento do Gweb. Lista entradas finalizadas combinando vendas internas do PDV (PV…) com NFC-e emitidas (NFCE…), mostrando Doc., Valor, datas de emissão/vencimento/recebimento e status (Recebida/Pendente/Cancelada). Busca por texto + filtros por Cliente, Status, Emissão inicial/final e Nº do documento (múltiplos por vírgula).",
      "Rel. de fechamento agora gera o PDF DIRETAMENTE pelo rail (item 'Rel. de fechamento'), sem precisar navegar até /relatorios/caixa. Usa o caixa aberto atual e adiciona 3 blocos vindos da análise do PDF do Gweb: (1) Cabeçalho fiscal completo (Fantasia/CNPJ/Endereço/Telefone), (2) Movimentações Manuais listando Suprimento e Sangria com motivo, (3) Caixa Físico com Calc. Sistema × Inf. Operador × Diferença por espécie.",
      "Mudança ISOLADA ao Frente de Caixa (módulo Mercado). PDV V2, Pedido Express, OrderCardChargeDialog, runMultiPayment, runTefPayment, pinpadService, tef-webservice, nfce-proxy, TEF v1.0/v1.1/v1.2-beta, Multi-Pagamento v1.6/v1.7, CashReport, PDVV2CloseCashDialog, impressão de produção/cupom e demais fluxos homologados NÃO foram tocados.",
    ],
  },
  {
    version: "1.18.2-beta",
    date: "2026-06-10",
    codename: "Frente de Caixa: busca/cadastro de cliente estilo Gweb",
    changes: [
      "Frente de Caixa (módulo Mercado) → tela 'Finalizando venda' → Etapa 2 Cliente: agora começa COLAPSADA com o estado 'Nenhum cliente vinculado' + botão 'INFORMAR CLIENTE' — espelha o PDV do Gweb. Os 3 campos abertos (Nome/Telefone/CPF) foram substituídos por um modal dedicado.",
      "Novo modal 'Buscar pessoas (clientes)': campo único que pesquisa CPF/CNPJ, nome OU telefone (debounce 280ms) sobre a base de clientes da loja. Lista resultados com nome + telefone + CPF, clique seleciona, duplo-clique já confirma.",
      "Botão 'CADASTRAR PESSOA' abre formulário rápido (Nome, Telefone, CPF) DENTRO do mesmo modal — sem sair do checkout. Ao salvar, o cliente é inserido em `customers` (multi-tenant via company_id) e já vinculado à venda.",
      "Quando o termo digitado tem 11+ dígitos e não retorna nada, aparece atalho 'Usar X como CPF/CNPJ no cupom' que preenche apenas o documento sem criar cadastro — preserva o fluxo de quem só quer o CPF na NFC-e.",
      "Cliente vinculado aparece como chip compacto na etapa 2 com botões 'Alterar' / 'Remover'. CPF/Telefone continuam fluindo para `runMultiPayment` e dali para o `nfce-proxy` exatamente como antes.",
      "Atalhos A–Z / Ctrl+1/2/3 / Home / Esc do checkout ficam SUSPENSOS enquanto o modal de cliente está aberto para não conflitar com a digitação.",
      "Mudança isolada: PDV V2, Pedido Express, OrderCardChargeDialog, runMultiPayment, nfce-proxy, TEF v1.0/v1.1/v1.2-beta, impressão e demais fluxos homologados não foram tocados.",
    ],
  },
  {
    version: "1.18.1-beta",
    date: "2026-06-10",
    codename: "Multi-pagamento v1.7.2 — auto-finalizar + trava até registrar",
    changes: [
      "Correção crítica no Multi-pagamento sequencial (PDV V2, Cobrar Comanda/Mesa, Pedido Express, Cobrar Pedido do Cardápio): quando o operador zerava o saldo restante (última cobrança TEF aprovada), o modal NÃO finalizava sozinho — esperava o clique manual em 'Finalizar venda (NFC-e)'. Se o operador fechava o modal/atualizava a tela nesse ponto, o PinPad já tinha cobrado o cliente mas a venda NUNCA era registrada no caixa, a NFC-e não saía e a comanda continuava em aberto (caso Bon Appetit / Mesa 11 / Comanda #268).",
      "Agora, assim que o restante chega a R$ 0,00, o modal AUTO-FINALIZA: dispara onConfirm (addSale + NFC-e quando aplicável) e só depois marca a cobrança como completed — sem depender do clique do operador.",
      "Trava de saída reforçada: o modal só libera o fechamento depois que markCompleted gravar status='completed' no servidor. Antes, com o restante zerado mas a venda ainda não registrada, o modal era 'fechável' — agora continua travado até a venda existir de fato.",
      "Se onConfirm falhar (ex.: erro de rede ao gravar a venda), o modal NÃO marca como completed: continua travado mostrando o erro, e o operador pode tentar finalizar de novo ou usar 'Cancelar e estornar tudo' (CNC automático nos TEFs aprovados).",
      "Nada de runTefPayment, pinpadService, tef-webservice, nfce-proxy, runMultiPayment, single-payment, splits por pessoas/itens, TEF v1.0/v1.1/v1.2-beta foi alterado — a mudança está isolada ao PDVV2SequentialPaymentDialog.",
    ],
  },
  {
    version: "1.18.0-beta",
    date: "2026-06-09",
    codename: "Frente de Caixa: menu de contexto e ajustes por item",
    changes: [
      "Frente de Caixa (módulo Mercado): novo MENU DE CONTEXTO ao clicar com o botão direito sobre qualquer item do carrinho — espelha o PDV do Gweb. Duas ações: 'Alterar preço' (atalho Home) e 'Editar detalhes' (atalho Ctrl+D). Atalhos agem sobre o último item tocado.",
      "Novo modal 'Alteração no preço do item': 3 modos selecionáveis com hotkeys — Desconto (−), Alteração no valor unitário (=) e Acréscimo (+). Tudo por linha, separado do desconto/acréscimo da venda toda. Múltiplas aplicações somam.",
      "Novo modal 'Editar detalhes' (aba IDENTIFICAÇÃO — aba ADICIONAIS ainda não disponível): edita quantidade, valor unitário e desconto da linha, mostra Código/GTIN, Quantidade convertida e Valor total recalculado em tempo real. Botão REMOVER (vermelho) no rodapé esquerdo descarta a linha.",
      "Cada linha do carrinho agora mostra o preço efetivo, com o preço original riscado quando há override, além de chips '− R$ X,XX desc.' / '+ R$ Y,YY acr.' separados. O Total da venda recalcula com tudo somado/abatido.",
      "Persistência: os ajustes por item são registrados em 'notes' da venda como linhas separadas ('Item N PRODUTO: preço A → B', 'Item N PRODUTO: desconto R$ X', 'Item N PRODUTO: acréscimo R$ Y') para auditoria. O pdv_sale_items grava unit_price efetivo da linha (override + desconto/acréscimo distribuídos).",
      "Nada de PDV V2, OrderCardChargeDialog, Pedido Express, TEF v1.0/v1.1/v1.2-beta, Multi-Pagamento v1.6/v1.7, NFC-e, impressão ou demais fluxos homologados foi tocado. Os novos diálogos vivem isolados em src/components/frente-caixa/.",
    ],
  },
  {
    version: "1.17.0-beta",
    date: "2026-06-09",
    codename: "Frente de Caixa: tela Finalizando venda",
    changes: [
      "Frente de Caixa (módulo Mercado): nova tela 'Finalizando venda' inspirada no PDV do Gweb, substituindo o diálogo de pagamento simples. Layout em 2 colunas — resumo financeiro à esquerda (produtos, desconto, acréscimo, total geral) e wizard de 3 etapas à direita.",
      "Etapa 1 — Pagamentos: multi-pagamento nativo com todas as formas ativas do canal PDV listadas, cada uma com atalho de letra (A, B, C, D…) para focar o campo de valor. Pressionar Enter com o campo vazio preenche automaticamente o saldo restante. Contador 'Pagamentos / Falta' em tempo real, com 'Falta' em vermelho enquanto > 0. SALVAR só habilita quando Falta = 0.",
      "Botão 'Desconto/Acréscimo (Home)' abre painel inline para informar valores em R$, recalculando o Total geral.",
      "Etapa 2 — Cliente (opcional, Ctrl+2): captura nome, telefone e CPF avulsos para a venda. Etapa 3 — Informações adicionais (opcional, Ctrl+3): observação livre. Ambas podem ser puladas.",
      "TEF integrado: linhas com forma TEF (PinPad/SmartPOS) disparam o PinPad pela engine runMultiPayment já homologada (v1.6) — tudo-ou-nada com estorno automático em caso de recusa parcial. NÃO altera pinpadService, tef-webservice, runTefPayment nem TEF v1.0/v1.1/v1.2-beta.",
      "Persistência: usa useCashRegister.addSale como antes, gravando combinedNotesFragment do multi-pagamento dentro de notes para auditoria e relatórios.",
      "Atalhos globais no modal: Ctrl+1/2/3 navega entre etapas, Home abre Desconto/Acréscimo, Esc fecha (com confirmação se houver valor alocado).",
      "Nada de PDV V2, OrderCardChargeDialog, Pedido Express, PDVV2PaymentDialog ou PDVV2MultiPaymentDialog foi tocado — a tela vive isolada em src/components/frente-caixa/FrenteCaixaCheckoutDialog.tsx e só é alcançável quando o módulo Mercado está ativo.",
      "NFC-e ainda NÃO é emitida automaticamente nesta tela (planejado para uma versão futura). Vendas ficam registradas no caixa normalmente.",
    ],
  },
  {
    version: "1.16.0-beta",
    date: "2026-06-09",
    codename: "Editar Pedido: entrega + forma de pagamento",
    changes: [
      "Editar Pedido (disponível em pedidos com status Pendente/Preparando) agora permite alterar TAMBÉM a forma de entrega e a forma de pagamento, além dos itens. Continua bloqueado a partir do status Pronto.",
      "Novo bloco 'Entrega' no diálogo: alterna entre Retirada e Entrega; quando Entrega, captura endereço livre e, em lojas que cobram por bairro, mostra select com a lista cadastrada. A taxa é recalculada na hora (modo bairro pega a fee do bairro escolhido; modo simples usa a taxa cidade configurada). Mudou para Retirada → taxa zera.",
      "Novo bloco 'Forma de pagamento': select com as formas ativas da loja. Dinheiro pede 'Troco para R$' (obrigatório). PIX mostra a chave configurada. A nova forma é gravada dentro de notes do pedido no mesmo formato lido pelo recibo (Pagamento: ... | Troco para R$ ... | Chave PIX: ...).",
      "Recibo é REIMPRESSO automaticamente quando entrega ou pagamento mudou (mesmo sem mexer em itens). A comanda de produção continua só saindo quando itens são adicionados/trocados — cozinha não recebe reimpressão desnecessária.",
      "Tag de auditoria expandida em notes: '[EDITADO HH:MM: itens+entrega+pagamento]' indica exatamente o que mudou.",
      "WhatsApp do cliente, quando ativo, agora menciona a mudança de modalidade (com endereço novo e taxa) e/ou a nova forma de pagamento.",
      "Nada de TEF (v1.0/v1.1/v1.2-beta), NFC-e, Multi-Pagamento, PDV V2 checkout, Pedido Express ou cardápio público foi alterado — a mudança fica isolada ao diálogo Editar Pedido.",
    ],
  },
  {
    version: "1.15.2-beta",
    date: "2026-06-06",
    codename: "Caixa: trava anti-duplo-clique na abertura",
    changes: [
      "Correção de bug: ao clicar duas vezes muito rápido em 'Abrir Caixa' (PDV V2, PDV V1 ou tela Caixas) o sistema criava DOIS caixas abertos simultâneos para a mesma loja, com um deles virando 'caixa fantasma' acumulando vendas que deveriam estar no outro.",
      "Trava tripla aplicada: (1) flag síncrona no hook impedindo segunda chamada antes da primeira terminar; (2) re-checagem no servidor antes do insert para impedir caixas vindos de outra aba/dispositivo; (3) índice único no banco (cash_registers_one_open_per_company) que garante que jamais existirão dois caixas com status='open' para a mesma loja, mesmo em condições extremas.",
      "Botão 'Abrir Caixa' agora fica desabilitado e mostra 'Abrindo...' enquanto a operação está em andamento, com o botão 'Cancelar' também travado para evitar fechamento acidental do diálogo no meio do processo.",
      "Nenhum fluxo de TEF, NFC-e, Pedido Express, Multi-Pagamento, impressão ou cardápio foi alterado.",
    ],
  },
  {
    version: "1.15.1-beta",
    date: "2026-06-06",
    codename: "Relatório de Vendas: comandas finalizadas",
    changes: [
      "Relatório de Vendas: vendas de comandas finalizadas agora deixam de aparecer como Balcão/PDV e passam a ser classificadas corretamente como Mesa (Garçom) ou Mesa QR.",
      "A identificação exibe o número da comanda e a origem mostra a mesa quando disponível, usando a venda já registrada no caixa para não duplicar faturamento.",
      "Correção isolada na aba Relatórios → Relatório de Vendas; PDV V2, Pedido Express, TEF, NFC-e, impressão e demais relatórios não foram alterados.",
    ],
  },
  {
    version: "1.15.0-beta",
    date: "2026-06-05",
    codename: "Menu lateral reorganizado: Cadastros + Ações de vendas",
    changes: [
      "Menu lateral 'Catálogo' renomeado para 'Cadastros' e reorganizado em dois sub-blocos: 'Produtos' (Categorias, Subcategorias, Produtos, Adicionais e — quando o módulo Mercado está ativo — Estoque) e 'Pessoas' (Clientes e Fornecedores).",
      "Novo menu 'Ações de vendas' agrupando Cupons, Campanhas de Vendas (quando o módulo está ativo) e Ver cardápio — antes esses itens ficavam misturados em Catálogo/Relatórios.",
      "Nova página 'Clientes' (rota /clientes) com CRUD completo (nome, telefone, CPF, data de nascimento, endereço, cidade/UF). O relatório existente em /relatorios/clientes continua intocado.",
      "Nova página 'Fornecedores' (rota /fornecedores) com CRUD completo (razão social, CNPJ/CPF, IE, contato, telefone, e-mail, endereço completo, observações, ativo/inativo). Nova tabela 'suppliers' isolada por empresa via RLS.",
      "Mudança válida para TODO o Comanda Tech (não restrita a quem tem mercado).",
      "Nenhum fluxo homologado foi alterado: TEF v1.0/v1.1/v1.2-beta, Multi-Pagamento, NFC-e, PDV V2, Pedido Express, impressão e cardápio público continuam idênticos.",
    ],
  },
  {
    version: "1.14.0-beta",
    date: "2026-06-05",
    codename: "Produtos: aba Mercado (Fase A) com tabela densa estilo Gdoor",
    changes: [
      "Página Produtos: quando o módulo Mercado está ativo, agora há duas abas — 'Cardápio' (visão atual, idêntica) e 'Mercado' (nova visão densa estilo Gdoor/Gweb).",
      "Aba Mercado: tabela paginada (50 itens por página) com colunas SKU, Produto, GTIN, Categoria, Unidade, Estoque, Mínimo, Preço e ação de editar. Busca única por nome/SKU/GTIN, filtro por categoria e filtro rápido 'Estoque ≤ mínimo' ou 'Sem GTIN'.",
      "Estoque é colorido por status (verde acima do mínimo, âmbar no mínimo, vermelho zerado, cinza sem controle) para localizar rupturas rapidamente, mesmo com 800+ itens.",
      "Edição reusa o mesmo diálogo existente — nenhum fluxo de cadastro, NFC-e, TEF, PDV V2 ou cardápio foi alterado. Quando o módulo Mercado está desligado, a página Produtos renderiza exatamente como antes.",
      "Próximas fases (não implementadas ainda): edição em página cheia tipo Gdoor, novos campos (peso, atacado, validade, CEST/ANP), sidebar de ações em massa.",
    ],
  },
  {
    version: "1.13.5-beta",
    date: "2026-06-04",
    codename: "NFC-e split: correção do colapso para 1 detPag",
    changes: [
      "Correção crítica no nfce-proxy (bloco pagamentos_split): a Fiscal Flow estava colapsando vendas multi-pagamento em um único <detPag> Dinheiro com o valor total (ex.: R$3 dinheiro + R$1 débito virava R$4 dinheiro na NFC-e). Causa: enviávamos o campo legado 'pagamento' (singular) junto com os arrays, e a Fiscal Flow priorizava o singular ignorando os arrays.",
      "Testes empíricos em homologação confirmaram: enviando apenas os arrays (pagamentos[], pag.detPag[], detPag[], formas_pagamento[]) a NFC-e sai com múltiplos <detPag> corretos. O fix removeu o campo 'pagamento' singular do bloco de split.",
      "Impacto: NFC-e de vendas com Dividir Formas passa a refletir corretamente cada forma cobrada (dinheiro + cartão + PIX, etc.) já a partir da próxima emissão.",
      "Não regrediu: single-payment (1 forma só), bloco TEF legado, runTefPayment, pinpadService, tef-webservice, TEF v1.0/v1.1/v1.2-beta, multi-pagamento sequencial v1.7, splits I9 — todos intocados. A mudança está isolada ao bloco 'if (pagamentos_split)' do nfce-proxy.",
    ],
  },
  {
    version: "1.13.4-beta",
    date: "2026-06-04",
    codename: "Multi-pagamento: valor manual + botão 'Usar restante'",
    changes: [
      "Modal 'Dividir formas de pagamento' (Pedido Express, Cobrar Pedido do Cardápio, Cobrar/Importar Comanda no PDV V2): o campo 'Valor' agora começa sempre VAZIO em cada cobrança. O operador escolhe a forma e digita o valor da linha — acabou o auto-preenchimento que fazia a 1ª forma absorver o total inteiro sem o operador perceber.",
      "Novo botão 'Usar restante (R$ X,XX)' abaixo do campo Valor: opcional, preenche o campo com o saldo restante em um clique — útil pra fechar a última linha sem digitar de novo.",
      "Permite dividir em 2, 3, 4 ou mais formas com segurança: cada linha exige escolha explícita de forma + valor.",
      "Nenhuma alteração em runTefPayment, pinpadService, tef-webservice, nfce-proxy, pagamentos_split, single-payment, splits por pessoas/itens, Importar Comanda, TEF v1.0/v1.1/v1.2-beta congelados ou reimpressão TEF.",
    ],
  },
  {
    version: "1.13.3-beta",
    date: "2026-06-04",
    codename: "Divisão por pessoas: NFC-e detalhada com itens rateados",
    changes: [
      "Cobrar pedido do cardápio + Pedido Express → Dividir por pessoas: a NFC-e parcial agora lista TODOS os itens do pedido com quantidade fracionada proporcional à parcela paga (ex.: pedido com 1× X-Burger dividido em 5 pessoas → cada parcela emite 0,200 × X-Burger), no lugar da linha única 'Parcela X - rachado'.",
      "Quantidade é fracionada (3 casas) e preço unitário preservado — somando as N parcelas o estoque baixa exatamente a quantidade original vendida (sem multiplicar a baixa pelo nº de pessoas).",
      "Centavos de arredondamento ajustados no último item de cada parcela para o somatório bater com o valor cobrado. Última parcela usa o saldo restante (remaining/totalPeople) para fechar 100% do pedido.",
      "A venda do caixa interno também passa a registrar os itens detalhados rateados — relatórios e ABC enxergam os produtos reais em vez de 'Divisão X/Y'.",
      "Nenhuma alteração em divisão por itens, PDV V2 comanda/mesa, TEF v1.0/v1.1/v1.2-beta, runTefPayment, pinpadService, nfce-proxy, multi-pagamento ou finalização do pedido.",
    ],
  },
  {
    version: "1.13.2-beta",
    date: "2026-06-04",
    codename: "Pedido Express: split por pessoas respeita nº de partes cobradas",
    changes: [
      "Pedido Express → Dividir por pessoas: corrigido bug em que o campo 'Cobrar quantas partes?' era ignorado no abatimento. Ex.: pedido R$170 dividido em 5 pessoas — ao cobrar 2 partes (R$68), o sistema só descontava 1 pessoa, permitindo que as mesmas partes fossem cobradas de novo.",
      "Agora o saldo restante é decrementado pelo número exato de partes pagas. Rótulo da venda, observação da NFC-e parcial e toast indicam o intervalo de pessoas cobradas (ex.: 'Pessoas 1–2/5').",
      "Nenhuma alteração em PDV V2 comanda/mesa, OrderCardChargeDialog (já corrigido na v1.13.1-beta), TEF v1.0/v1.1/v1.2-beta, runTefPayment, pinpadService, nfce-proxy, multi-pagamento sequencial ou rachar item.",
    ],
  },
  {
    version: "1.13.1-beta",
    date: "2026-06-04",
    codename: "Cobrar pedido: continuidade do split por pessoas",
    changes: [
      "Cobrar pedido do cardápio → Dividir por pessoas: ao reabrir a cobrança depois que uma ou mais pessoas já pagaram, o diálogo agora mostra automaticamente 'Pessoa X de N — restam Y' e o campo 'Cobrar quantas partes?' já vem limitado ao restante.",
      "Acabou o problema de o sistema esquecer o nº original de pessoas e tratar o saldo residual como um novo split (ex.: pedido R$170 dividido em 6 — depois de 4 pagamentos, o sistema mostrava 'Nº de pessoas: 2' como se fosse novo, em vez de reconhecer que faltam 2 das 6 originais).",
      "Estado do split persiste no próprio pedido (paid_items.split_state) e é limpo automaticamente quando o pedido é quitado.",
      "Nenhuma alteração em PDV V2 comanda/mesa, Pedido Express, runTefPayment, pinpadService, nfce-proxy, multi-pagamento, rachar item ou TEF v1.0/v1.1/v1.2-beta.",
    ],
  },
  {
    version: "1.13.0-beta",
    date: "2026-06-04",
    codename: "Dividir por pessoas: cobrar várias partes na mesma transação",
    changes: [
      "PDV V2 → Cobrar Comanda/Mesa → Dividir por pessoas: novo campo 'Cobrar agora quantas partes?' permite cobrar mais de uma pessoa de uma só vez (ex.: comanda de R$100 dividida em 4 — uma pessoa paga 3 partes = R$75 numa única cobrança e outra paga 1 parte = R$25).",
      "Funciona em todas as pessoas: na primeira pessoa o operador escolhe o nº de pessoas + quantas partes cobrar agora; nas pessoas seguintes o sistema mostra quantas restam e o campo já vem limitado ao restante.",
      "Cada cobrança gera uma única venda (com TEF próprio, se aplicável) e — quando o módulo fiscal está ativo — uma NFC-e parcial com observação automática ('pessoas X a Y de N').",
      "Caminho legado 'Distribuir entre os itens' (rachar) continua disponível e inalterado para quem prefere dividir item a item.",
      "Não foi alterado: runTefPayment, pinpadService, tef-webservice, nfce-proxy, single-payment, multi-pagamento sequencial (v1.7), rachar item, importar comanda single-payment, TEF v1.0/v1.1/v1.2-beta congelados.",
    ],
  },
  {
    version: "1.12.1-beta",
    date: "2026-06-04",
    codename: "Multi-pagamento v1.7.1 — NFC-e opcional quando não há TEF",
    changes: [
      "Correção no modal 'Dividir formas' (Pedido Express, Cobrar Pedido do Cardápio, Cobrar Comanda/Mesa no PDV V2): NFC-e não é mais emitida automaticamente quando a divisão é feita só em dinheiro/PIX manual.",
      "Agora o modal mostra o seletor 'Só Venda / Venda com NFC-e' — mesma lógica do pagamento de uma forma só. Padrão: Só Venda.",
      "Quando qualquer uma das cobranças é TEF (cartão), a NFC-e continua sendo emitida automaticamente (obrigatória por lei) — o seletor é substituído por um aviso informando isso.",
      "Lojas sem o módulo Fiscal não veem o seletor.",
      "Nada de TEF v1.0/v1.1/v1.2-beta, pinpadService, tef-webservice, nfce-proxy, pagamentos_split, single-payment ou splits I9 foi alterado.",
    ],
  },
  {
    version: "1.12.0-beta",
    date: "2026-06-04",
    codename: "Multi-pagamento sequencial v1.7 (modal travado + retomada)",
    changes: [
      "Multi-pagamento agora é SEQUENCIAL: ao clicar em 'Dividir formas' (Pedido Express, Cobrar Pedido do Cardápio, Importar/Cobrar Comanda/Mesa no PDV V2), o modal cobra uma forma de cada vez. Você escolhe a forma, informa o valor e clica em 'Cobrar' — a cobrança vai direto pro PinPad/registro e o restante atualiza. Repita até zerar.",
      "Quando a forma escolhida é TEF, agora aparece o seletor de modalidade (Crédito à vista, Débito, Parcelado com Nº de parcelas + ADM/Loja, ou PIX) ANTES da cobrança — igual ao fluxo single-payment do PDV V2.",
      "Modal TRAVADO enquanto houver valor restante: não dá pra fechar com X, clicar fora ou apertar ESC. A saída só libera depois de quitar 100% ou usar 'Cancelar e estornar tudo' (que faz CNC automático no PinPad em cada TEF aprovado).",
      "RETOMADA AUTOMÁTICA: se o sistema cair / o navegador fechar / faltar luz no meio da cobrança, ao reabrir o mesmo pedido/comanda/mesa o sistema reidrata as cobranças já aprovadas e mostra o restante exato para continuar de onde parou. Persistência via nova tabela 'pdv_v2_open_charges'.",
      "Recusa NÃO faz rollback automático: se a 3ª cobrança for negada, as 2 aprovadas continuam ativas e o operador escolhe outra forma/valor pro restante. Rollback só acontece se o operador clicar em 'Cancelar e estornar tudo'.",
      "NFC-e (quando módulo fiscal está ativo) só é emitida ao FINALIZAR com restante = 0, mantendo o mesmo formato 'pagamentos_split' com várias <detPag>.",
      "Liberado para TODAS as lojas com PDV V2.",
      "NÃO foi alterado: runTefPayment, pinpadService, tef-webservice, nfce-proxy, PDVV2PaymentDialog single-payment, splits I9 (por pessoa / por itens), Importar Comanda, TEF v1.0/v1.1/v1.2-beta congelados, reimpressão TEF.",
    ],
  },
  {
    version: "1.11.1-beta",
    date: "2026-06-03",
    codename: "Cupons: troca de Frete grátis por Cupom secreto",
    changes: [
      "No cadastro de Cupons, a opção 'Frete grátis' foi substituída pela opção 'Cupom secreto'. Cupons marcados como secretos NÃO aparecem no banner do topo do cardápio — só são aceitos quando o cliente digita o código manualmente.",
      "Removidos do banco os campos 'coupons.free_shipping' e 'orders.free_shipping_applied' (não estavam em uso por nenhuma loja em produção). Em troca, foi criada a coluna 'coupons.is_secret'.",
      "Nenhuma outra lógica do cardápio, checkout, PDV, TEF, NFC-e, impressão ou WhatsApp foi alterada.",
    ],
  },
  {
    version: "1.11.0-beta",
    date: "2026-06-03",
    codename: "Cupons de desconto (cardápio online) — beta",
    changes: [
      "Novo menu lateral 'Cupons' (em Catálogo): permite criar cupons de desconto para o cardápio online com código, tipo (percentual % ou valor fixo R$), valor mínimo do pedido (se em branco, vale pro cardápio todo), desconto máximo opcional, toggle de cupom secreto (não aparece no banner), validade inicial/final e limite de usos.",
      "Cardápio público mostra um banner clicável no topo (acima das categorias) sempre que houver cupom ativo. Ao tocar, abre uma janela com todos os cupons disponíveis, regras e botão de copiar código.",
      "No checkout do cardápio, o cupom é aplicado AUTOMATICAMENTE quando o cliente atinge as condições (subtotal ≥ valor mínimo). Aparece linha 'Desconto' verde no resumo e o total já desconta o cupom. Cliente também pode digitar/colar um código manualmente.",
      "Mensagem do WhatsApp do pedido agora inclui 1 linha 'Cupom: CODIGO  -R$ X,XX' quando há cupom aplicado. Sem cupom, a mensagem fica idêntica à atual.",
      "Pedidos passam a registrar 'coupon_code' e 'discount_amount' (campos opcionais e nullable — pedidos antigos continuam funcionando).",
      "Escopo desta fase: APENAS cardápio online. PDV, PDV V2, Pedido Express, Mesa QR, Garçom, TEF (v1.0/v1.1/v1.2-beta), Multi-Pagamento e NFC-e NÃO foram tocados.",
    ],
  },
  {
    version: "1.10.1-beta",
    date: "2026-06-03",
    codename: "Cadastro de produto para mercado — beta",
    changes: [
      "Fase 3.1 do módulo Mercado: o diálogo 'Novo Produto' agora exibe o bloco 'Dados de mercado' (GTIN, SKU, unidade de medida, regra de tributação, controle de estoque com saldo inicial e estoque mínimo) APENAS para lojas com o módulo Mercado ativo.",
        "Aviso amarelo educativo no diálogo lista o que está faltando ('Sem GTIN não bipa', 'Sem regra tributária NFC-e pode rejeitar'), sem bloquear o salvamento.",
      "Quando 'Controlar estoque' é marcado e há saldo inicial > 0, o sistema cria automaticamente um movimento do tipo 'initial' em stock_movements — o produto já aparece em /estoque com saldo e histórico correto.",
      "Lojas SEM o módulo Mercado não veem nenhuma diferença no cadastro de produtos — o diálogo continua exatamente como antes.",
      "Nenhum fluxo de PDV V2, Pedido Express, TEF (v1.0/v1.1/v1.2-beta), Multi-Pagamento, NFC-e ou impressão foi alterado.",
    ],
  },
  {
    version: "1.10.0-beta",
    date: "2026-06-03",
    codename: "Controle de Estoque (mercado) — beta",
    changes: [
      "Fase 3 do módulo Mercado: produtos agora podem ter controle de estoque individual. Em Produtos, ao editar um item, aparece a seção 'Controle de estoque' (apenas para lojas com módulo Mercado ativo) com saldo atual e estoque mínimo.",
      "Baixa automática no Frente de Caixa: cada venda dispara automaticamente o débito do estoque dos produtos com 'Controle de estoque' ativado, registrando o movimento no histórico. Produtos sem rastreio continuam vendendo normalmente, sem qualquer mudança de comportamento.",
      "Nova tela 'Estoque' (rota /estoque) no menu Catálogo, visível só com módulo Mercado: lista todos os produtos rastreados com saldo atual, alerta de mínimo (vermelho = zerado, amarelo = abaixo do mínimo, verde = OK), filtros por categoria/busca e exportação CSV.",
      "Ações por produto: Entrada manual (nota fiscal de fornecedor), Saída manual (perda/quebra), Ajuste de inventário (define um saldo novo direto) e Histórico completo de movimentos com data, tipo, quantidade, saldo resultante e observação.",
      "Nova tabela 'stock_movements' grava todo o histórico (vendas, entradas, saídas, ajustes). Função SQL 'apply_stock_movement' faz a baixa atomicamente — se o produto não tem rastreio ativo, é no-op silencioso.",
      "Não regressivo: lojas sem módulo Mercado não veem nada novo. Pedido Express, PDV V2, TEF v1.0/v1.1/v1.2-beta, Multi-Pagamento, NFC-e e impressão NÃO foram tocados. A baixa só ocorre via Frente de Caixa nesta fase — Pedido Express ainda não dá baixa (será fase seguinte se validado em piloto).",
    ],
  },
  {
    version: "1.9.0-beta",
    date: "2026-06-03",
    codename: "Frente de Caixa (mercado) — beta",
    changes: [
      "Nova tela 'Frente de Caixa' (rota /frente-caixa) disponível apenas para lojas com o módulo 'Mercado' ativo — pensada para mini mercados e lojas de conveniência que vendem produtos com código de barras.",
      "Operação 100% por leitor: input sempre focado, bipe → produto entra na lista, Enter adiciona, F2 finaliza, F4 remove o último item, Esc cancela a venda.",
      "Busca aceita GTIN exato, SKU exato ou nome parcial. Atalho '3*7891234567890' adiciona 3 unidades de uma vez. Feedback sonoro curto para sucesso/erro.",
      "Finalização reusa o diálogo de pagamento do PDV V2 (canal PDV) e registra a venda no caixa atual via fluxo já existente — nenhum dado novo no banco.",
      "TEF integrado ainda NÃO disponível na Frente de Caixa nesta versão beta; ao escolher uma forma TEF, o sistema avisa para usar o PDV V2. NFC-e/impressão automática virão na próxima iteração.",
      "Item 'Frente de Caixa' aparece no menu lateral apenas quando o módulo 'Mercado' está ativo. PDV V2, Pedido Express, Cobrança, TEF v1.0/v1.1/v1.2-beta e Multi-Pagamento NÃO foram alterados.",
      "Rollout isolado: módulo 'Mercado' continua desligado por padrão — ativar manualmente em Admin → Módulos da empresa apenas em lojas-piloto de mercado.",
    ],
  },
  {
    version: "1.8.5",
    date: "2026-06-02",
    codename: "Formas Entrega/Retirada para todas as lojas",
    changes: [
      "Divisão de formas de pagamento por modalidade (Entrega/Retirada) liberada para TODAS as lojas — antes era exclusivo da Lancheria I9 e Bon Appetit.",
      "Em Configurações → Formas de Pagamento, nas abas Cardápio Online e Pedido Express, agora aparecem os toggles 'Mostrar para Entrega' e 'Mostrar para Retirada' em cada forma.",
      "Cardápio Online e Pedido Express passam a filtrar automaticamente as formas conforme a modalidade escolhida pelo cliente. PDV (caixa) continua sem essa divisão.",
      "Padrão preservado: lojas existentes já tinham 'show_for_delivery' e 'show_for_pickup' = true por default, portanto nada some sem ação manual.",
      "Nenhum fluxo de TEF, NFC-e, Multi-Pagamento, impressão ou PDV V2 foi alterado.",
    ],
  },
  {
    version: "1.8.4-beta",
    date: "2026-06-02",
    codename: "Layout V3 densidade Agilize (beta)",
    changes: [
      "Layout V3 reaproximado da foto de referência: hierarquia única no PED #xxx (13pt bold) — nome da loja e demais textos em 8.5pt uniforme.",
      "Removida faixa de modalidade em texto invertido; agora usa 3 linhas literais de '#' espelhando o cupom Agilize.",
      "Densidade aumentada: line-height 0.95, padding 1mm, zero linhas em branco entre seções, cabeçalho da tabela cola direto nos itens.",
      "Quebra de página suprimida (page-break-inside: avoid) — recibo sai em fluxo contínuo numa única folha térmica.",
      "V1 e V2 permanecem 100% intactos. Mudança isolada ao V3 da Lancheria I9.",
    ],
  },
  {
    version: "1.8.3-beta",
    date: "2026-06-02",
    codename: "Layout V3 grade 48 cols (beta)",
    changes: [
      "Layout V3 do recibo agora usa grade FIXA de 48 colunas monoespaçadas (padrão ESC/POS Epson TM-T20/TM-T88 @ 80mm), fonte Courier New 9pt, line-height 1.0.",
      "Estrutura espelhada da foto de referência: PED #xxx centralizado, faixa de modalidade em texto invertido, tabela 'REF| DESCRICAO ... VALOR', itens com nome + preço unitário, complementos numerados '[N] item' indentados em 3 colunas e linha de subtotal 'Q X R$ X,XX = R$ X,XX' alinhada à direita.",
      "Totais com pipe a 17 colunas ('TOTAL ITENS | ... R$ X,XX'), TOTAL GERAL em negrito, metadados (COD/Criado em/Impresso em) no mesmo padrão pipe.",
      "Largura fixa 80mm, altura automática, sem centralização excessiva — apenas nome da loja, PED e modalidade são centralizados.",
      "Layouts V1 e V2 permanecem 100% intactos. Rollout V3 continua isolado por loja (atualmente só Lancheria da I9).",
    ],
  },
  {
    version: "1.8.2-beta",
    date: "2026-06-02",
    codename: "Layout V3 ESC/POS Epson (beta)",
    changes: [
      "Layout V3 do recibo (PDV V2 / Pedido Express / Cardápio Online) reescrito como template ESC/POS Epson TM-T20/TM-T88 — fonte Courier New única, line-height 1.0, ~40% menos espaçamento entre itens e alinhamento por colunas fixas (42 cols @ 80mm, 32 cols @ 58mm).",
      "Coluna VALOR sempre alinhada à direita em todas as linhas (descrição, totais e meta) usando padding por caractere.",
      "Faixa de modalidade (BALCAO/ENTREGA/RETIRADA) agora sai em texto invertido (fundo preto / texto branco), equivalente ao reverse video ESC/POS (GS B 1), substituindo os '#####' do V3 anterior.",
      "Separadores em ASCII ('-' repetido na largura total) no lugar de <hr> dashed.",
      "Layouts V1 e V2 permanecem 100% intactos. Rollout V3 continua isolado por loja (atualmente só Lancheria da I9).",
      "Nenhum fluxo de TEF (v1.0/v1.1/v1.2-beta), NFC-e, Multi-Pagamento, PDV V2 ou auto_printer.py foi alterado — mudança 100% no HTML gerado no lado web.",
    ],
  },
  {
    version: "1.8.1-beta",
    date: "2026-06-02",
    codename: "Layout V3 fiel ao Agilize (beta)",
    changes: [
      "Layout V3 de impressão reescrito do zero para replicar fielmente o recibo térmico Agilize: cabeçalho da loja (nome, endereço, CNPJ), PED #xxx centralizado, bloco cliente com Fones/endereço/Bairro/Ponto de referência, faixa de modalidade (TELE ENTREGA/MOTOBOY, RETIRADA NO LOCAL, BALCÃO, MESA) em ASCII, tabela REF|DESCRICAO|VALOR com adicionais numerados entre colchetes, TOTAL ITENS + FRETE + TOTAL GERAL separados, bloco de PAGAMENTO/TROCO, COD/Criado em/Impresso em, faixa PREVISTO e rodapé com URL do app.",
      "Fonte alterada para Lucida Console/Consolas com tamanhos compactos (8-11pt), eliminando os títulos gigantes do V3 anterior.",
      "Reescrita aplicada tanto no auto_printer.py (cardápio online / WhatsApp) quanto em pdvV2Print.ts (PDV V2 / Pedido Express) — versões visualmente idênticas.",
      "Layouts V1 e V2 permanecem 100% intactos. Nenhuma loja sem 'Layout V3' selecionado teve qualquer alteração.",
      "Nenhum fluxo de TEF (v1.0/v1.1/v1.2-beta), NFC-e, Multi-Pagamento ou banco de dados foi alterado.",
    ],
  },
  {
    version: "1.8.0-beta",
    date: "2026-06-02",
    codename: "Layout de impressão V3 (beta)",
    changes: [
      "Novo Layout V3 de impressão (beta) disponível em Configurações → Impressão → Layout de Impressão (visível apenas para Admin Master). Pode ser selecionado por loja sem afetar as demais.",
      "Comanda de produção V3: cabeçalho 'PEDIDO' gigante, separadores em ASCII, faixa de tipo do pedido (ENTREGA/RETIRADA/MESA/BALCÃO) em destaque, bloco 'Pronto até' com moldura e adicionais empilhados em caixa alta.",
      "Recibo V3 no auto_printer.py: layout denso inspirado no recibo V3 do PDV V2, com PED #, totais destacados e badge de Entrega/Retirada. Reimpressão a partir do Painel mantém o mesmo visual.",
      "Layouts V1 e V2 permanecem 100% intactos — nenhuma loja que não selecionar V3 manualmente terá qualquer alteração visual.",
      "Nenhum fluxo de TEF, NFC-e, PDV V2, Multi-Pagamento ou banco de dados foi alterado.",
    ],
  },
  {
    version: "1.7.1-beta",
    date: "2026-06-02",
    codename: "Taxas Cidade/Interior opcionais",
    changes: [
      "Configurações → Entrega: cada taxa (Cidade e Interior) agora tem um interruptor próprio. Lojas que não atendem interior podem desativar essa região e o campo de valor fica bloqueado.",
      "Cardápio Online e Pedido Express: regiões desativadas somem do checkout. Quando só uma região está ativa, o cliente vê apenas 'Entrega' (sem precisar escolher entre Cidade/Interior).",
      "Padrão preservado: lojas existentes continuam com as duas regiões ativas — nenhuma mudança visível até desligar manualmente.",
      "Nenhum fluxo de TEF, NFC-e, impressão, PDV V2 ou Multi-Pagamento foi alterado.",
    ],
  },
  {
    version: "1.7.0-beta",
    date: "2026-06-02",
    codename: "Múltiplos endereços por cliente",
    changes: [
      "Cardápio Online: clientes recorrentes agora podem manter mais de um endereço cadastrado. Ao digitar o telefone, aparece o seletor 'Endereços salvos' com botões 'Novo' (para cadastrar outro) e 'Gerenciar' (para escolher um padrão ou excluir).",
      "Comportamento atual preservado: o primeiro endereço continua sendo preenchido automaticamente como antes; quem só tem um endereço não vê nenhuma mudança no fluxo.",
      "Backfill automático: todos os endereços já cadastrados foram migrados para a nova base de múltiplos endereços, marcados como padrão.",
      "Nenhum fluxo de pedido, cobrança, NFC-e, impressão ou PDV foi alterado.",
    ],
  },
  {
    version: "1.6.2-beta",
    date: "2026-06-02",
    codename: "Filtros avançados em Pedidos",
    changes: [
      "Aba Pedidos: novos filtros por Forma de Entrega (Entrega/Retirada), Origem (Cardápio Online, Balcão/Express, Mesa, Mesa via QR) e Forma de Pagamento (lista dinâmica, incluindo 'Múltiplas formas' e 'Sem pagamento').",
      "Totalizadores reativos abaixo dos filtros: número de pedidos, faturamento, ticket médio e cancelados — recalculam conforme os filtros aplicados.",
      "Filtros são puramente de visualização: nenhum fluxo de cobrança, TEF, NFC-e, impressão ou banco de dados foi alterado.",
    ],
  },
  {
    version: "1.6.1-beta",
    date: "2026-06-02",
    codename: "Dividir formas em todos os checkouts (beta)",
    changes: [
      "Botão 'Dividir formas' movido para DENTRO do checkout de pagamento — agora aparece como um link discreto logo abaixo da seleção da forma de pagamento, em vez de ficar solto ao lado de 'Enviar para Cozinha'.",
      "Disponível em todos os checkouts: Pedido Express (Finalizar Pedido), Cobrar Pedido do Cardápio e Importar/Cobrar Comanda/Mesa no PDV V2.",
      "O link só aparece quando faz sentido: não é exibido quando a comanda está em divisão por pessoas ou por itens (TEF v1.1 congelado).",
      "Mesma lógica tudo-ou-nada: TEF recusado → estorno automático de todas as cobranças já aprovadas.",
      "Fluxos congelados (TEF v1.0/v1.1/v1.2-beta, pagamento simples, divisão por pessoas/itens) não foram alterados.",
    ],
  },
  {
    version: "1.6.0-beta",
    date: "2026-06-02",
    codename: "Dividir formas de pagamento (beta)",
    changes: [
      "Novo botão 'Dividir formas' no Pedido Express (etapa 5): permite cobrar a venda em várias formas de pagamento ao mesmo tempo (ex.: parte no TEF/cartão, parte em dinheiro, ou em vários cartões).",
      "Cobranças TEF são executadas em sequência no PinPad. Se qualquer uma for recusada, todas as já aprovadas são estornadas automaticamente e a venda não é registrada (modo tudo-ou-nada).",
      "Quando o módulo Fiscal está ativo, a NFC-e sai com várias formas de pagamento (detPag) em uma única nota.",
      "Rollout piloto: apenas Pedido Express. PDV V2, Cobrança de Pedido e Finalizar Venda virão em uma próxima atualização após validação.",
      "Fluxos congelados (TEF v1.0/v1.1/v1.2-beta, pagamento simples, comandas, mesas) não foram alterados.",
    ],
  },
  {
    version: "1.5.4",
    date: "2026-06-02",
    codename: "Desconto restaurado na cobrança",
    changes: [
      "Campo 'Desconto (R$)' restaurado no diálogo de pagamento — aparece novamente em Cobrar Pedido do Cardápio, Importar e Cobrar Mesa, Pedido Express e Finalizar Venda do PDV V2.",
    ],
  },
  {
    version: "1.5.3",
    date: "2026-06-02",
    codename: "Cobrança rachada por pessoas",
    changes: [
      "Cobrar pedido do cardápio (Lancheria I9) - divisão por pessoas: a parcela cobrada (ex.: R$ 7 de R$ 30) entra no caixa com o valor real e o pedido fica como 'parcial', mantendo o botão Cobrar disponível para o saldo restante até a quitação total.",
    ],
  },
  {
    version: "1.5.2",
    date: "2026-06-02",
    codename: "Correção de cobrança fracionada",
    changes: [
      "Cobrar pedido do cardápio (Lancheria I9): ao dividir um item e cobrar apenas uma fração na primeira cobrança, o sistema agora respeita o valor selecionado em vez de marcar o item inteiro como pago. O botão Cobrar continua disponível para o saldo restante.",
    ],
  },
  {
    version: "1.5.1",
    date: "2026-06-02",
    codename: "Quebra de texto no modal de cobrança",
    changes: [
      "Modal 'Cobrar pedido' (PDV V2): nomes longos de itens com muitos adicionais agora quebram em várias linhas em vez de truncar, evitando o corte visual do modal.",
    ],
  },
  {
    version: "1.5.0",
    date: "2026-06-01",
    codename: "TEF v1.1 + Pedido Express + Mesa QR",
    changes: [
      "Sistema de versionamento com badge discreto no canto inferior direito",
      "TEF v1.1 consolidado (Lancheria I9)",
      "Pedido Express com todas as formas de pagamento",
      "Cardápio Mesa QR (rota /mesa/:slug)",
      "Campanhas de vendas via WhatsApp",
    ],
  },
];

/** Formata data YYYY-MM-DD para DD/MM/YYYY (pt-BR). */
export function formatReleaseDate(iso: string): string {
  const [y, m, d] = iso.split("-");
  return `${d}/${m}/${y}`;
}